### PR TITLE
fix: argocd-cm empty data label nil pointer fix

### LINKED ISSUE #3491: Bug: not able to save chart repo when argocd-cm has empty data label
### 📜 Description

When argocd-cm has no data label, then the code throws nil pointer and a toast pops-up with the same message.

### 👟 Reproduction steps

1. In argocd-cm from resource browser, remove the data label completely.
2. Now go and add a chart repo, in the logs we see nil pointer being thrown.

### 👍 Expected behavior

The chart repo should have been saved without the error toast.

### 👎 Actual Behavior

The chart repo is not being saved with nil pointer toast error on the ui.

### ☸ Kubernetes version

Client Version: v1.26.4
Server Version: v1.26.4

### Cloud provider

<details>
Azure 
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3624

### PR DESCRIPTION
**Pull request by prakash100198**
# Description

When data label in argocd-cm is not present then a new chart repo is not getting added and throws nil pointer as we append the chart repo details in argocd-cm, cm.Data is nil and later this map was being used to set a value in one of it's key, hence throwing nil pointer 
Fixes #3491 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Tested Locally
- Tested by deploying in my cluster
- Test Scenarios:- 
    1. Devtron installed via helm without argo-cd enabled and remove the data label from argocd-cm to reproduce this issue, now add a chart repo, previously it was throwing nil pointer, after this pr it was working fine
    2. Now installed argo-cd module(this will cover a scenario when a user switches from helm to argocd with empty argocd-cm then any new chart repo addition will not fail), and install the same application with argocd, it was working fine
    3. Go to argo-cd and check if the application is getting registered in argocd or not and also check if sync is happening or not, it was working fine in that case too.
  
- Test Scenarios after code refactoring:- 
      1. Create new chart repo, check secret is being created or not, and it must not get stored in argocd-cm and check on argocd as well it must get registered there, also try saving same chart url and see if it affect the pre-deployed apps, in this case it's working fine.
      2. Create new chart repo with same name as existing names, it should now show toast as this chart name exist.
      3. After creating new public chart repo, check by deploying few charts from that repo, using gitops/helm both are working fine.
      4. Check for private charts, existing behaviour is expected for private chart, except when new private chart with same name as existing ones is added it must throw toast error.
      5. Update any pre-existing chart, it's updated value should get updated in argocd-cm, and after updating any newly added chart repo it's updated value should get patched in it's corresponding secret.
      6. Try deleting chart repo, for pre-existing chart repos whose entry is in argocd-cm , that entry must get deleted and for newly added chart the corresponding secret should get deleted.
      7. For pre-existing charts deployed, check it's behaviour if a new repo is added with the same url but with diff chart name.
      8. Check an deployed chart behaviour via argocd after deleting the repo entry from argocd-cm and after deleting the secret as well (syncing must happen from github repo in argocd which is working correctly).
      9. Try saving chart repo with uppercase names and lowercase names since secret creation doesn't support uppercase chart names.

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by Apollo9999** [comment]
To fix the "nil pointer" issue related to the empty data label in ArgoCD ConfigMap (argocd-cm), you can follow these steps:

Step1Locate the ConfigMap definition:

In your Kubernetes cluster, find the ConfigMap resource associated with ArgoCD.
Typically, the ConfigMap name is argocd-cm in the argocd namespace.

Step2 Edit the ConfigMap YAML:
Retrieve the YAML definition of the ConfigMap by running the command: kubectl get configmap argocd-cm -n argocd -o yaml.
Save the output to a local file for editing.

Step3 Update the YAML file:
Open the YAML file in a text editor.
Look for the data section within the ConfigMap definition.
Check if there is an empty data label (e.g., data: {}).
Replace the empty data label with a nil value by removing the data field entirely. It should look like this:
     apiVersion: v1
    kind: ConfigMap
    metadata:
    name: argocd-cm
    namespace: argocd
Step4 Apply the updated ConfigMap:

Apply the updated YAML file to your Kubernetes cluster by running the command: kubectl apply -f <path-to-updated-file>.
By removing the empty data label, you prevent any potential nil pointer errors that could occur due to accessing empty data in the ConfigMap. Keep in mind that this fix assumes that the empty data label is not necessary for your specific use case. If you have any specific data entries required within the ConfigMap, make sure to include them accordingly in the data section.

Please note that modifying the ArgoCD ConfigMap should be done with caution, as it can affect the behavior and configuration of your ArgoCD installation. It's recommended to back up the existing ConfigMap and test the changes in a non-production environment before applying them to a production cluster.

File: pkg/chartRepo/ChartRepositoryService.go [hunk 1]
```diff
@@ -172,13 +172,15 @@ func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (
 			if err != nil {
 				return nil, err
 			}
-			data, err := impl.updateRepoData(cm.Data, request)
-			if err != nil {
-				impl.logger.Warnw(" config map update failed", "err", err)
-				continue
+			if cm.Data != nil {
```
Comment (nishant-d) [inline pkg/chartRepo/ChartRepositoryService.go:175]: what if CM doesn't exists

File: pkg/chartRepo/ChartRepositoryService.go [hunk 2]
```diff
@@ -172,13 +172,15 @@ func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (
...
+				data, err := impl.updateRepoData(cm.Data, request)
+				if err != nil {
```
Comment (nishant-d) [inline pkg/chartRepo/ChartRepositoryService.go:177]: propagate the error and rollback any other modifications

Comment (nishant-d) [reply pkg/chartRepo/ChartRepositoryService.go:177]: propagate all the errors and rollback changes if any

File: pkg/chartRepo/ChartRepositoryService.go [hunk 3]
```diff
@@ -172,13 +172,15 @@ func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (
...
+					impl.logger.Warnw(" config map update failed", "err", err)
+					continue
+				}
+				cm.Data = data
+				_, err = impl.K8sUtil.UpdateConfigMap(impl.aCDAuthConfig.ACDConfigMapNamespace, cm, client)
 			}
-			cm.Data = data
-			_, err = impl.K8sUtil.UpdateConfigMap(impl.aCDAuthConfig.ACDConfigMapNamespace, cm, client)
 		} else {
 			secretLabel := make(map[string]string)
```
Comment (nishant-d) [inline pkg/chartRepo/ChartRepositoryService.go:185]: why diff treatment for private and public repo? can we have an unified mechanism ?

**Review by nishant-d — CHANGES_REQUESTED** [review]

File: pkg/chartRepo/ChartRepositoryService.go (hunk 3 above)
Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go:185]: Actually argo-cd creates secret kind object for every helm chart, so for private chart repos there is password, and username also which is a part of that manifest so in this way a private chart is being registered by argocd. But for public chart also argocd creates this secret kind object so ideally we should add both type of charts public and private via creating secet kind object which can be done in another ticket.

File: pkg/chartRepo/ChartRepositoryService.go (hunk 1 above)
Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go]: added a check for empty cm

Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go]: do test for cm empty

File: pkg/chartRepo/ChartRepositoryService.go (hunk 2 above)
Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go]: have changed the code here, secrets will get created in case of public as well as private, also db updation is happening in transaction so rollback will happen in case of errors.

File: pkg/chartRepo/ChartRepositoryService.go [hunk 4]
```diff
@@ -99,22 +100,38 @@ func NewChartRepositoryServiceImpl(logger *zap.SugaredLogger, repoRepository cha
...
 }
 
 func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (*chartRepoRepository.ChartRepo, error) {
+	allChartsRepos, err := impl.repoRepository.FindAll()
+	if err != nil {
+		impl.logger.Errorw("error in getting list of all chart repos", "err", err)
+		return nil, err
+	}
+	if len(allChartsRepos) == 0 {
+		return nil, errors.New("no chart repo found in db")
```
Comment (nishant-d) [inline pkg/chartRepo/ChartRepositoryService.go:128]: is it an error or expected condition ?

**Review by nishant-d — CHANGES_REQUESTED** [review]

File: pkg/chartRepo/ChartRepositoryService.go (hunk 4 above)
Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go:132]: it's just handling an a corner case when error is nil and if somehow there are no entries in db for chart repos

Comment (prakash100198) [reply pkg/chartRepo/ChartRepositoryService.go]: have handled this case differently, if no data is present will return nil and validation result only, and then no need to trigger chart sync

**Review by subhashish-devtron — APPROVED** [review]

**Review by nishant-d — APPROVED** [review]
