### PR TITLE
fix: namespace cache delete actions

### LINKED ISSUE #5847: Bug: cluster deleted but namespace is present in autocomplete api

### PR DESCRIPTION
**Pull request by iamayushm**
# Description

Fixes #5847 

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/delete/DeleteService.go [hunk 1]
```diff
@@ -68,18 +75,38 @@ func NewDeleteServiceImpl(logger *zap.SugaredLogger,
...
 }
 
+func (impl DeleteServiceImpl) DeleteClusterSecret(deleteRequest *cluster.ClusterBean, err error) error {
+	// kubelink informers are listening this secret, deleting this secret will inform kubelink that this cluster is deleted
+	k8sClient, err := impl.K8sUtil.GetCoreV1ClientInCluster()
+	if err != nil {
+		impl.logger.Errorw("error in getting in cluster k8s client", "err", err, "clusterName", deleteRequest.ClusterName)
+		return nil
+	}
+	secretName := fmt.Sprintf("%s-%v", cluster.SECRET_NAME, deleteRequest.Id)
```
Comment (nishant-d) [inline pkg/delete/DeleteService.go:105]: extract common secret name builder

**Review by nishant-d — CHANGES_REQUESTED** [review]

**Review by nishant-d — APPROVED** [review]
