### PR TITLE
fix:Not able to change Authentication Type for Prometheus.

### LINKED ISSUE #874: Not able to change Authentication Type for Prometheus.
Once cluster is save with Prometheus and auth-type as basic then afterwards not able to change it from basic auth to 
Anonymous.

Checklist:

* [ ] I've searched in the docs and FAQ for my answer
* [ ] I've included steps to reproduce the bug.

### PR DESCRIPTION
**Pull request by adi6859**
# Description
Once cluster is save with Prometheus and auth-type as basic then afterwards not able to change it from basic auth to
Anonymous.

Fixes #874 

## How Has This Been Tested?
* [x] tests are performed locally.
* [ ] tests are also done by deploying image on vm.

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by subhashish-devtron — DISMISSED** [review]

**Review by vikramdevtron — DISMISSED** [review]

**Review by subhashish-devtron — DISMISSED** [review]
LGTM

**Review by subhashish-devtron — APPROVED** [review]

File: pkg/cluster/ClusterService.go [hunk 1]
```diff
@@ -493,10 +494,10 @@ func (impl *ClusterServiceImpl) Update(ctx context.Context, bean *ClusterBean, u
 	model.PrometheusEndpoint = bean.PrometheusUrl
 
 	if bean.PrometheusAuth != nil {
-		if bean.PrometheusAuth.UserName != "" {
+		if bean.PrometheusAuth.UserName != "" || bean.PrometheusAuth.IsAnonymous {
```
Comment (vikramdevtron) [inline pkg/cluster/ClusterService.go:497]: what if bean.PrometheusAuth.UserName=="" while IsAnonymous, will this work with empty username

Comment (adi6859) [reply pkg/cluster/ClusterService.go:497]: yes , when we have empty username it is a case of anonymous type ,I have tested for these cases.

**Review by vikramdevtron — APPROVED** [review]
