### PR TITLE
fix: Helm Apps permissions do not allow Terminal or Logs view

### LINKED ISSUE #4106: Bug: Helm Apps permissions do not allow Terminal or Logs view
### 📜 Description

I have assigned full permissions to everything to single user, he have full permissions in "Devtron Apps", in "Helm Apps" and in "Kubernetes Resources" he should be on par with Super admin. 
full_perm

What I need is to have the user be able to view logs and terminal in "Helm Apps" view. where he is unable now:

cant_get_log

### 👟 Reproduction steps

Create user, assign permissions (I'm using OIDC from keycloak ) the user is assigned to correct email since when I switch him to be Super admin all works fine.

Deploy Helm Chart (I'm using my own from custom repo, should not have effect on this issue ) 

Deploy (this works fine)
Try to get Logs or Console ( I get permission denied..., If I go through Resource Browser it works fine, the same user have all permissions for cluster resources ) It does not work where it is most important.

### 👍 Expected behavior

Able to easily assign user permissions to deploy helm chart and have permissions to edit it, view logs and terminal.

### 👎 Actual Behavior

I can deploy,edit, delete... can't view logs or enter terminal, which is critical functionality for us.

### ☸ Kubernetes version

Client Version: v1.27.6+k3s1
Kustomize Version: v5.0.1
Server Version: v1.27.6+k3s1

### Cloud provider

<details>

</details>

### 🌍 Browser

Opera

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

No idea, full almost super admin permissions do not do it, I can switch the user to super admin and it will work.. but that s no use to me. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6239

### PR DESCRIPTION
**Pull request by Ashish-devtron**
# Description

Fixes #4106 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/user/casbin/rbac.go [hunk 1]
```diff
@@ -111,12 +111,11 @@ type EnforcerImpl struct {
 // Enforce is a wrapper around casbin.Enforce to additionally enforce a default role and a custom
 // claims function
 func (e *EnforcerImpl) Enforce(token string, resource string, action string, resourceItem string) bool {
-	return e.enforce(token, resource, action, resourceItem)
+	return e.enforce(token, resource, action, strings.ToLower(resourceItem))
```
Comment (vikramdevtron) [inline pkg/user/casbin/rbac.go:114]: we can do it inside the enforcer for common for all

**Review by vikramdevtron — APPROVED** [review]
