### PR TITLE
fix: helm and gitOps pipeline feature gap changes

### LINKED ISSUE #2868: Fix: remove feature gaps between gitOps and helm pipelines
### 🔖 Feature description

1. Align deployment statuses of helm pipelines to that of gitOps pipelines. 
2. Fix bulk hibernate/un-hibernate apis.
3. Optimise app status fetch apis for helm pipelines.
4. Fix resource delete issue in helm pipelines.

### 🎤 Pitch

Remove `healthy`,`degraded` statuses and have statuses like `Succeeded` & `Failed`. Also, fix a bug where older deployment statuses change into `Degraded` when new deployments are triggered.

### ✌️ Solution

Replace Application Health statuses with devtron specific terms which are `Succeeded` and `Failed`. `In Progress` will be remain.

### 🔄️ Alternative

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kartik-579**
# Description
Remove feature gaps between helm and gitOps pipelines. 

Fixes #2868 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] Tested for deployment statuses of old apps.
- [x] Tested bulk hibernate/un-hibernate apis
- [x] Tested query performance of app status fetch

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/pipeline/CdHandler.go [hunk 1]
```diff
@@ -270,52 +270,54 @@ func (impl *CdHandlerImpl) UpdatePipelineTimelineAndStatusByLiveApplicationFetch
...
-		return nil
+		impl.Logger.Errorw("error in getting latest triggers of helm pipelines which are stuck in non terminal statuses", "err", err)
+		return err
 	}
-	impl.Logger.Infow("checking helm app status for deployment triggers", "pipelineOverrides", pipelineOverrides)
-	for _, pipelineOverride := range pipelineOverrides {
+	impl.Logger.Infow("checking helm app status for non terminal deployment triggers", "wfrList", wfrList)
+	for _, wfr := range wfrList {
+		//TODO: remove hardcoding
+		if time.Now().Sub(wfr.UpdatedOn) < 2*time.Minute {
```
Comment (kripanshdevtron) [inline pkg/pipeline/CdHandler.go:282]: make this time configurable

**Review by kripanshdevtron — APPROVED** [review]
