### PR TITLE
fix: Port number fix in helm app

### LINKED ISSUE #3829: Bug: Appearing empty port number in Helm applications in Devtron resources page.
### 📜 Description

Upon opening any Helm application and inspecting the associated service, we observe that the port number is missing, despite the service manifest containing the designated service port.

ss

### 👟 Reproduction steps

1. Deploy a helm chart which have service k8s resource.
2. Try to see the URL of service in Devtron app page

### 👍 Expected behavior

It should show the URL of service along with service port number.

### 👎 Actual Behavior

Right now service UL showing , port number is missing.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5218

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Fixes #3829

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/k8s/K8sCommonService.go [hunk 1]
```diff
@@ -342,3 +343,112 @@ func (impl *K8sCommonServiceImpl) GetCoreClientByClusterId(clusterId int) (*kube
...
+			if spec != nil {
+				ports, ok := spec["ports"]
+				if !ok {
+					impl.logger.Errorw("ports not found in resource tree, unable to extract port no")
+					return resourceTree, nil
+				}
+				portList := ports.([]interface{})
+				for _, portItem := range portList {
+					if portItem.(map[string]interface{}) != nil {
+						portNumbers := portItem.(map[string]interface{})["port"]
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:376]: let's add ok bool validation for every type assertion. example - 
portNumbers := portItem.(map[string]interface{})["port"] --> portNumbers, ok := portItem.(map[string]interface{})["port"]

File: pkg/k8s/K8sCommonService.go [hunk 2]
```diff
@@ -342,3 +343,112 @@ func (impl *K8sCommonServiceImpl) GetCoreClientByClusterId(clusterId int) (*kube
...
+						portNumber := portNumbers.(int64)
+						if portNumber != 0 {
+							portsService = append(portsService, portNumber)
+						}
+					}
+				}
+			} else {
+				impl.logger.Errorw("spec doest not contain data", "err", spec)
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:384]: why not returning here? also, key value pair is wrong...given spec printing err

File: pkg/k8s/K8sCommonService.go [hunk 3]
```diff
@@ -342,3 +343,112 @@ func (impl *K8sCommonServiceImpl) GetCoreClientByClusterId(clusterId int) (*kube
...
+			}
+		}
+		if kind == EndpointsKind {
+			subsetsField, ok := portHolder.ManifestResponse.Manifest.Object["subsets"]
+			if !ok {
+				impl.logger.Errorw("spec not found in resource tree, unable to extract port no")
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:390]: not looks like error, can be warn or info

File: pkg/k8s/K8sCommonService.go [hunk 4]
```diff
@@ -342,3 +343,112 @@ func (impl *K8sCommonServiceImpl) GetCoreClientByClusterId(clusterId int) (*kube
...
+				return resourceTree, nil
+			}
+			if subsetsField != nil {
+				subsets := subsetsField.([]interface{})
+				for _, subset := range subsets {
+					subsetObj := subset.(map[string]interface{})
+					if subsetObj != nil {
+						ports, ok := subsetObj["ports"]
+						if !ok {
+							impl.logger.Errorw("ports not found in resource tree endpoints, unable to extract port no")
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:400]: incorrect level of log

File: pkg/k8s/K8sCommonService.go [hunk 5]
```diff
@@ -342,3 +343,112 @@ func (impl *K8sCommonServiceImpl) GetCoreClientByClusterId(clusterId int) (*kube
...
+							}
+						}
+					}
+				}
+			}
+		}
+		if kind == "EndpointSlice" {
+			portsField, ok := portHolder.ManifestResponse.Manifest.Object["ports"]
+			if !ok {
+				impl.logger.Errorw("ports not found in resource tree endpoint, unable to extract port no")
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:418]: incorrect level of log

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by kartik-579 — DISMISSED** [review]

**Review by kartik-579 — APPROVED** [review]
