### PR TITLE
fix: normal Refresh after triggering gitops deployment to avoid sync delay in argo

### LINKED ISSUE #4046: Feature: Support for ArgoCD webhook
### 🔖 Feature description

Argo CD polls Git repositories every three minutes to detect changes to the manifests. To eliminate this delay from polling, a webhook could be triggered to trigger a sync as soon as deployment is triggered on Devtron.

Refer: https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/

### 🎤 Pitch

Developers sometimes have to wait for upto 3 minutes for a deployment to be initiated by ArgoCD, thus degrading user experience.

### ✌️ Solution

In scenarios where there are more than a couple of thousand ArgoCD applications, there is a visible performance degradation and the 3 minutes `--app-resync` parameter may take more than 3 minutes as the cycle over-runs. 
To prevent this, the `--app-resync` can be increased and a webhook can be configured to trigger the deployment.

### 🔄️ Alternative

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6058

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Fixes #4046

Above issue is being resolved with this PR, doing a refresh on argocd will do a sync.
## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: client/argocdServer/ArgoClientWrapperService.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+) *ArgoClientWrapperServiceImpl {
+	return &ArgoClientWrapperServiceImpl{
+		logger:    logger,
+		acdClient: acdClient,
+	}
+}
+
+func (impl *ArgoClientWrapperServiceImpl) GetArgoAppWithNormalRefresh(context context.Context, argoAppName string) error {
+	refreshType := bean.RefreshTypeNormal
+	impl.logger.Debugw("trying to normal refresh application through get ")
```
Comment (kartik-579) [inline client/argocdServer/ArgoClientWrapperService.go:31]: add argoAppName

File: pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go [hunk 2]
```diff
@@ -473,3 +473,9 @@ func (impl *AppStoreDeploymentHelmServiceImpl) SaveTimelineForACDHelmApps(instal
 func (impl *AppStoreDeploymentHelmServiceImpl) UpdateInstalledAppAndPipelineStatusForFailedDeploymentStatus(installAppVersionRequest *appStoreBean.InstallAppVersionDTO, triggeredAt time.Time, err error) error {
 	return nil
 }
+
+// This is being done as in ea mode wire argocd service is being binded to helmServiceImpl due to which we are restricted to implement this here.
```
Comment (kartik-579) [inline pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go:477]: add TODO that this needs to be refactored in separate story

File: pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go [hunk 3]
```diff
@@ -473,3 +473,9 @@ func (impl *AppStoreDeploymentHelmServiceImpl) SaveTimelineForACDHelmApps(instal
...
+// RefreshAndUpdateACDApp this will update chart info in acd app if required in case of mono repo migration and will refresh argo app
+func (impl *AppStoreDeploymentHelmServiceImpl) RefreshAndUpdateACDApp(installAppVersionRequest *appStoreBean.InstallAppVersionDTO, ChartGitAttribute *util.ChartGitAttribute, isMonoRepoMigrationRequired bool, ctx context.Context) error {
+	return nil
```
Comment (kartik-579) [inline pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go:480]: return err that this is not implemented

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by vikramdevtron — APPROVED** [review]

**Review by kartik-579 — APPROVED** [review]
