### PR TITLE
fix: inducing overridden DockerRegistryId in case docker registry is overridden

### LINKED ISSUE #4179: Bug: Image pull secret does not automatically inject the registry credentials into the target namespace if it is used as an override in the build configuration
### 📜 Description

In Devtron UI when we configure image pull secret feature to auto inject the registry credentials in target cluster when we used different container registry in base build configuration and overridden.

Base Build configuration have ECR regsitry.
sss

Override build configuration

sss3

Error and pod manifest do hadn’t imagePullSecret and target environment also.
sss45

### 👟 Reproduction steps

1. Create an Devtron app and add 2 container registry for example one as ECR and 2nd one for Dockerhub.
2. Use dockerhub as imagepull secret to auto inject registry credentials .
3. And try to deploy application.

### 👍 Expected behavior

It should be auto injected imagePull Secret and pass in rollout manifest.

### 👎 Actual Behavior

Currently it is not happening as aspecting.

### ☸ Kubernetes version

1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by prakash100198**
# Description

When we override the base build config (docker registry), at the time of inducing the image pull secret in the manifest we only checked for base build config, and not the overridden docker registry config. This pr aims at fixing the same issue.

Fixes #4179 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Tested multiple scenarios such as:-
    1. without ci template override.
    2. with template override and with same creds and container registry.
    3. base had ecr setup and override had docker setup.
    4. base had docker container registry and override had ecr.
    5. in case of auto and manual cd trigger

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/dockerRegistry/DockerRegistryIpsConfigService.go [hunk 1]
```diff
@@ -154,6 +138,40 @@ func (impl DockerRegistryIpsConfigServiceImpl) HandleImagePullSecretOnApplicatio
...
+		return nil, err
+	}
+
+	if ciPipeline.IsExternal && ciPipeline.ParentCiPipeline == 0 {
+		impl.logger.Warn("Ignoring for external ci")
+		return nil, nil
+	}
+
+	if ciPipeline.CiTemplate == nil {
+		impl.logger.Warn("returning as ciPipeline.CiTemplate is found nil")
```
Comment (vikramdevtron) [inline pkg/dockerRegistry/DockerRegistryIpsConfigService.go:154]: what is response in this case

File: pkg/dockerRegistry/DockerRegistryIpsConfigService.go [hunk 2]
```diff
@@ -154,6 +138,40 @@ func (impl DockerRegistryIpsConfigServiceImpl) HandleImagePullSecretOnApplicatio
...
+		return nil, nil
+	}
+
+	dockerRegistryId := ciPipeline.CiTemplate.DockerRegistryId
+	if len(*dockerRegistryId) == 0 {
+		impl.logger.Warn("returning as dockerRegistryId is found empty")
+		return nil, nil
```
Comment (vikramdevtron) [inline pkg/dockerRegistry/DockerRegistryIpsConfigService.go:161]: throw custom error

**Review by vikramdevtron — DISMISSED** [review]

**Review by subhashish-devtron — APPROVED** [review]

File: pkg/dockerRegistry/DockerRegistryIpsConfigService.go (hunk 2 above)
Comment (prakash100198) [reply pkg/dockerRegistry/DockerRegistryIpsConfigService.go:161]: This custom error was not being thrown earlier also, so don't know it may impact other flows also outside this function which will increase the scope of this maybe

**Review by vikramdevtron — APPROVED** [review]
