### PR TITLE
Docker checkout path Fix

### LINKED ISSUE #2617: Bug: Project Checkout Feature not working for old Apps
### 📜 Description

After upgrade to v0.6.6, old apps with checkout path configured is not working.

### 👟 Reproduction steps

1.) Old Apps with checkout path configured
2.) Upgrade to v0.6.6, after upgrade functionality is not working.

### 👍 Expected behavior

Even after upgrade build should get successful

### 👎 Actual Behavior

Build is getting failed since path on which it is looking for dockerfile, does not exist.

### ☸ Kubernetes version

EKS 1.21

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kripanshdevtron**
# Description
Dockerfile checkout path was not working for earlier created apps. Checkout path was getting appended twice to actual dockerfile path

Fixes #2617 

## How Has This Been Tested?
- [x] Apps whose checkout path is present in old structure
- [x] Apps created with checkout path is working fine

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by nishant-d — APPROVED** [review]

File: pkg/pipeline/CiService.go [hunk 1]
```diff
@@ -409,12 +409,12 @@ func (impl *CiServiceImpl) buildWfRequestForCiPipeline(pipeline *pipelineConfig.
 		ciBuildConfigBean = templateOverrideBean.CiBuildConfig
 		templateOverride := templateOverrideBean.CiTemplateOverride
 		checkoutPath = templateOverride.GitMaterial.CheckoutPath
-		dockerfilePath = filepath.Join(checkoutPath, templateOverride.DockerfilePath)
+		dockerfilePath = templateOverride.DockerfilePath
```
Comment (pghildiyal) [inline pkg/pipeline/CiService.go:412]: should name be absoluteDockerfilePath ?
