### PR TITLE
Logs secret data obfuscation

### LINKED ISSUE #499: Obfuscate / Skip logging sensitive info in the console until debug mode is enabled
Obfuscate or skip logging sensitive info (passwords, keys etc) in the console until debug mode is enabled

Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Some micro-services log sensitive info in the console logs, which should not be done until debug mode is enabled. Check the following micro-services:

1. Git-sensor
2. Devtron Orchestrator
3. Ci-runner

**Expected behavior**

Logs should not contain any sensitive info like passwords, keys, tokens etc.

**Current behavior** 

Some micro-services log sensitive info on console.

### PR DESCRIPTION
**Pull request by kripanshdevtron**
# Description

Secret info was getting logged. Info is obfuscated using struct tags in code and the log level changed to Debug.

Fixes #499 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Restarted Server and secret info were encrypted.

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles
* [x] I have added all the required unit/api test cases

### CODE REVIEW

File: internal/util/GitCliUtil.go [hunk 1]
```diff
@@ -102,7 +102,7 @@ func (impl *GitCliUtil) Init(rootDir string, remoteUrl string, isBare bool) erro
 }
 
 func (impl *GitCliUtil) Clone(rootDir string, remoteUrl string, username string, password string) (response, errMsg string, err error) {
-	impl.logger.Infow("input", rootDir, remoteUrl, username, password)
+	impl.logger.Infow("input", rootDir, remoteUrl, username)
```
Comment (manish-agrawal-ai) [inline internal/util/GitCliUtil.go:105]: I am assuming this format is correct

**Review by manish-agrawal-ai — APPROVED** [review]

File: internal/util/GitCliUtil.go (hunk 1 above)
Comment (kripanshdevtron) [reply internal/util/GitCliUtil.go:105]: Yes it is correct
