### PR TITLE
fix: chart repository fixes

### LINKED ISSUE #1306: [Chart Repositories] On Delete "Chart Repo" information doesn't update in config-map "argocd"
**On Delete for Full mode and Hyperion mode**

**Steps to Replicate**
1. Go to Dashboard > Global Configurations >  Chart Repositories
2. Delete your chart repository you are not using for any application
3. Now open the cm "argocd-cm"
4. Observe the chart repository 

**Actual Output**
chart details remain persistent in the file as it

**Expected Output**
Chart details should get removed/updated in the control manager "argocd-cm"

**On Delete for Hyperion mode**
1. Go to Dashboard > Global Configurations >  Chart Repositories
2. Delete any chart repository you are using for any application.

 **Actual Output**
chart repo gets deleted.

**Expected Output**
chart repo should not get deleted if any app is deployed by one of it's charts.

**On Update for Full mode and Hyperion mode**

**Steps to Replicate**
1. Go to Dashboard > Global Configurations >  Chart Repositories
2. update name and toggle disable button of your chart repository.
5. Now refresh the page.
6. . Observe the chart repository 

 **Actual Output**
chart repo details are not getting updated in db but updated in argo-cd cm .

**Expected Output**
Chart details should get updated with provided details.

AB#368

### PR DESCRIPTION
**Pull request by gireesh-devtron**
# Description
Blocked update and delete chart repository if any helm app is deployed with this chart
Fixes #1306 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested the functionality for both Full mode and hyperion mode

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles
* [ ] I have added all the required unit/api test cases

### CODE REVIEW

File: api/chartRepo/ChartRepositoryRestHandler.go [hunk 1]
```diff
@@ -176,6 +176,13 @@ func (handler *ChartRepositoryRestHandlerImpl) UpdateChartRepo(w http.ResponseWr
 		common.WriteJsonResp(w, err, "Unauthorized User", http.StatusUnauthorized)
 		return
 	}
+
+	token := r.Header.Get("token")
```
Comment (kripanshdevtron) [inline api/chartRepo/ChartRepositoryRestHandler.go:180]: why do we need to move logic here ??

File: pkg/chartRepo/ChartRepositoryService.go [hunk 2]
```diff
@@ -148,15 +148,14 @@ func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (
 	return chartRepo, nil
 }
 
-func (impl *ChartRepositoryServiceImpl) UpdateChartRepo(request *ChartRepoDto) (*chartRepoRepository.ChartRepo, error) {
+func (impl *ChartRepositoryServiceImpl) UpdateChartRepo(request *ChartRepoDto, chartRepoId int) (*chartRepoRepository.ChartRepo, error) {
```
Comment (kripanshdevtron) [inline pkg/chartRepo/ChartRepositoryService.go:151]: why do we need chartRepoId ??

File: pkg/chartRepo/repository/ChartRepoRepository.go [hunk 3]
```diff
@@ -245,13 +245,30 @@ type ChartRepo struct {
 	Deleted     bool                `sql:"deleted,notnull"`
 	sql.AuditLog
 }
+type ChartRepoWithDeploymentCount struct {
```
Comment (kripanshdevtron) [inline pkg/chartRepo/repository/ChartRepoRepository.go:248]: use composition here

**Review by kripanshdevtron — APPROVED** [review]
