### PR TITLE
Enhancement: Kubernetes api refactoring

### LINKED ISSUE #3641: enhancement: Kubernetes Api Refactoring
### 📜 Description

Refactoring Kubernetes Apis in K8sCapacityService, K8sClientService, K8sUtil, K8sApplicationService, ClusterService, K8sApplicationServiceImpl 

### 👟 Reproduction steps

NA

### 👍 Expected behavior

NA

### 👎 Actual Behavior

NA

### ☸ Kubernetes version

v1.26.6

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4359

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Kubernetes Api Refactoring
Fixes #3641

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by Ashish-hacker-0 — APPROVED** [review]

File: client/k8s/application/Application.go [hunk 1]
```diff
@@ -80,6 +90,19 @@ type ResourceListResponse struct {
 	Resources unstructured.UnstructuredList `json:"resources,omitempty"`
 }
 
+func (impl *K8sClientServiceImpl) GetRestConfigByClusterId(ctx context.Context, clusterId int) (*rest.Config, error) {
+	_, span := otel.Tracer("orchestrator").Start(ctx, "K8sApplicationService.GetRestConfigByClusterId")
+	defer span.End()
+	cluster, err := impl.clusterService.FindById(clusterId)
+	if err != nil {
+		impl.logger.Errorw("error in getting cluster by ID", "err", err, "clusterId")
```
Comment (kartik-579) [inline client/k8s/application/Application.go:98]: add clusterId value

File: client/k8s/application/Application.go [hunk 2]
```diff
@@ -80,6 +90,19 @@ type ResourceListResponse struct {
...
+		return nil, err
+	}
+	clusterConfig := cluster.GetClusterConfig()
+	restConfig, err := impl.k8sUtil.GetRestConfigByCluster(&clusterConfig)
```
Comment (kartik-579) [inline client/k8s/application/Application.go:102]: handle error

File: api/cluster/EnvironmentRestHandler.go [hunk 3]
```diff
@@ -514,29 +509,23 @@ func (impl EnvironmentRestHandlerImpl) GetEnvironmentConnection(w http.ResponseW
...
 	}
+
 	responseObj := &ClusterReachableResponse{
 		ClusterReachable: true,
 		ClusterName:      clusterBean.ClusterName,
 	}
-	err = impl.k8sApplicationService.FetchConnectionStatusForCluster(k8sClientSet, clusterBean.Id)
+	err = impl.k8sClientService.FetchConnectionStatusForCluster(k8sClientSet, clusterBean.Id)
 	if err != nil {
 		responseObj.ClusterReachable = false
```
Comment (kartik-579) [inline api/cluster/EnvironmentRestHandler.go:530]: add log

File: client/k8s/application/Application.go [hunk 4]
```diff
@@ -447,3 +470,46 @@ func (impl K8sClientServiceImpl) PatchResource(ctx context.Context, restConfig *
...
+			}
+		} else {
+			err = fmt.Errorf("Validation failed : %v", err)
+		}
+	} else if err == nil && string(response) != "ok" {
+		err = fmt.Errorf("Validation failed with response : %s", string(response))
+	}
+	return err
+}
+func (impl *K8sClientServiceImpl) CreateK8sClientSet(restConfig *rest.Config) (*kubernetes.Clientset, error) {
```
Comment (kartik-579) [inline client/k8s/application/Application.go:503]: this is in no way related to devtron's k8s client, move this to raw k8s dir

File: client/k8s/application/util/K8sUtil.go [hunk 5]
```diff
@@ -66,11 +71,21 @@ type ClusterConfig struct {
 	CAData                string
 }
 
-const DEFAULT_CLUSTER = "default_cluster"
-const BearerToken = "bearer_token"
-const CertificateAuthorityData = "cert_auth_data"
-const CertData = "cert_data"
-const TlsKey = "tls_key"
+const (
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:74]: move constants to k8sUtilBean

File: client/k8s/application/util/K8sUtil.go [hunk 6]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
 	return nil
 }
 
+func (impl K8sUtil) GetK8sConfigAndClients(clusterConfig *ClusterConfig) (*rest.Config, *http.Client, *kubernetes.Clientset, error) {
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:455]: why client**s**?

File: client/k8s/application/util/K8sUtil.go [hunk 7]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+	restConfig, err := impl.GetRestConfigByCluster(clusterConfig)
+	if err != nil {
+		impl.logger.Errorw("error in getting rest config by cluster", "err", err, "clusterName", clusterConfig.ClusterName)
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:458]: either clusterConfig is never empty or this will panic

File: client/k8s/application/util/K8sUtil.go [hunk 8]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+		return nil, nil, nil, err
+	}
+	k8sHttpClient, err := OverrideK8sHttpClientWithTracer(restConfig)
+	if err != nil {
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:462]: add log

File: client/k8s/application/util/K8sUtil.go [hunk 9]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+		return nil, nil, nil, err
+	}
+	k8sClientSet, err := kubernetes.NewForConfigAndClient(restConfig, k8sHttpClient)
+	if err != nil {
+		impl.logger.Errorw("error in getting client set by rest config", "err", err, "restConfig", restConfig)
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:467]: restConfig consists of token, not preferrable to print it

File: client/k8s/application/util/K8sUtil.go [hunk 10]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+		return nil, nil, nil, err
+	}
+	return restConfig, k8sHttpClient, k8sClientSet, nil
+}
+
+func (impl K8sUtil) DiscoveryClientGetLiveZCall(cluster *ClusterConfig) ([]byte, error) {
+	_, _, k8sClientSet, err := impl.GetK8sConfigAndClients(cluster)
+	if err != nil {
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:475]: add log

File: client/k8s/application/util/K8sUtil.go [hunk 11]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+	}
+	k8sClientSet, err := kubernetes.NewForConfigAndClient(restConfig, k8sHttpClient)
+	if err != nil {
+		impl.logger.Errorw("error in getting client set by rest config", "err", err, "restConfig", restConfig)
+		return nil, nil, nil, err
+	}
+	return restConfig, k8sHttpClient, k8sClientSet, nil
+}
+
+func (impl K8sUtil) DiscoveryClientGetLiveZCall(cluster *ClusterConfig) ([]byte, error) {
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:473]: if this clusterConfig is devtron's object, move this method to k8sClient

File: client/k8s/application/util/K8sUtil.go [hunk 12]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+	_, _, k8sClientSet, err := impl.GetK8sConfigAndClients(cluster)
+	if err != nil {
+		return nil, err
+	}
+	//using livez path as healthz path is deprecated
+	response, err := impl.GetLiveZCall(LiveZ, k8sClientSet)
+	return response, err
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:480]: we cannot be sure that this err will always be handled in the parent func, handle

File: client/k8s/application/util/K8sUtil.go [hunk 13]
```diff
@@ -437,6 +452,39 @@ func (impl K8sUtil) DeleteJob(namespace string, name string, clusterConfig *Clus
...
+
+}
+func (impl K8sUtil) GetLiveZCall(path string, k8sClientSet *kubernetes.Clientset) ([]byte, error) {
+	response, err := k8sClientSet.Discovery().RESTClient().Get().AbsPath(path).DoRaw(context.Background())
+	return response, err
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:485]: same as above

File: client/k8s/application/util/K8sUtil.go [hunk 14]
```diff
@@ -815,3 +863,109 @@ func (impl K8sUtil) GetKubeVersion() (*version.Info, error) {
 	}
 	return k8sServerVersion, err
 }
+
+func (impl K8sUtil) GetConfigAndClientsInCluster() (*v12.CoreV1Client, error) {
```
Comment (kartik-579) [inline client/k8s/application/util/K8sUtil.go:867]: why client**s**?

File: pkg/cluster/ClusterService.go [hunk 15]
```diff
@@ -113,15 +112,15 @@ func GetClusterBean(model repository.Cluster) ClusterBean {
 	return bean
 }
 
-func (bean ClusterBean) GetClusterConfig() util.ClusterConfig {
-	return util.ClusterConfig{
+func (bean ClusterBean) GetClusterConfig() util3.ClusterConfig {
```
Comment (kartik-579) [inline pkg/cluster/ClusterService.go:115]: almost copy of method with same name implemented on ClusterService. eliminate one.

File: pkg/cluster/ClusterService.go [hunk 16]
```diff
@@ -689,22 +657,8 @@ func (impl ClusterServiceImpl) DeleteFromDb(bean *ClusterBean, userId int32) err
...
-	// this secret was created for syncing cluster information with kubelink
-	httpClientFor, err := rest.HTTPClientFor(restConfig)
-	if err != nil {
-		impl.logger.Errorw("error occurred while overriding k8s client", "reason", err)
-		return nil
-	}
-	k8sClient, err := v12.NewForConfigAndClient(restConfig, httpClientFor)
+	k8sClient, err := impl.K8sUtil.GetConfigAndClientsInCluster()
 	if err != nil {
-		impl.logger.Errorw("error creating k8s client", "error", err)
```
Comment (kartik-579) [inline pkg/cluster/ClusterService.go:707]: add log

File: util/k8s/k8sApplicationService.go [hunk 17]
```diff
@@ -872,8 +869,8 @@ func (impl *K8sApplicationServiceImpl) GetAllApiResources(ctx context.Context, c
 	return response, nil
 }
 
-func (impl *K8sApplicationServiceImpl) GetResourceList(ctx context.Context, token string, request *ResourceRequestBean, validateResourceAccess func(token string, clusterName string, request ResourceRequestBean, casbinAction string) bool) (*util.ClusterResourceListMap, error) {
-	resourceList := &util.ClusterResourceListMap{}
+func (impl *K8sApplicationServiceImpl) GetResourceList(ctx context.Context, token string, request *ResourceRequestBean, validateResourceAccess func(token string, clusterName string, request ResourceRequestBean, casbinAction string) bool) (*util2.ClusterResourceListMap, error) {
+	resourceList := &util2.ClusterResourceListMap{}
 	clusterId := request.ClusterId
 	clusterBean, err := impl.clusterService.FindById(clusterId)
```
Comment (kartik-579) [inline util/k8s/k8sApplicationService.go:875]: below whole block can be replaced by GetRestConfigByClusterId

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: client/k8s/application/util/K8sUtil.go (hunk 6 above)
Comment (Shivam-nagar23) [reply client/k8s/application/util/K8sUtil.go:455]: other clients are used in getting metrics client in some calls.

File: client/k8s/application/util/K8sUtil.go (hunk 7 above)
Comment (Shivam-nagar23) [reply client/k8s/application/util/K8sUtil.go:458]: it is never empty

File: pkg/k8s/K8sCommonService.go [hunk 18]
```diff
@@ -0,0 +1,415 @@
...
+		var kind, name, namespace string
+		kind = impl.extractResourceValue(resourceItem, "kind")
+		name = impl.extractResourceValue(resourceItem, "name")
+		namespace = impl.extractResourceValue(resourceItem, "namespace")
+
+		if appId == "" {
+			appId = strconv.Itoa(appDetail.ClusterId) + "|" + namespace + "|" + (appDetail.AppName + "-" + appDetail.EnvironmentName)
+		}
+		if strings.Compare(kind, "Service") == 0 || strings.Compare(kind, "Ingress") == 0 {
+			group := impl.extractResourceValue(resourceItem, "group")
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:189]: this too

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: pkg/k8s/K8sCommonService.go [hunk 19]
```diff
@@ -0,0 +1,464 @@
...
+
+func (impl *K8sCommonServiceImpl) CreateResource(ctx context.Context, request *ResourceRequestBean) (*k8s.ManifestResponse, error) {
+	resourceIdentifier := &openapi.ResourceIdentifier{
+		Name:      &request.K8sRequest.ResourceIdentifier.Name,
+		Namespace: &request.K8sRequest.ResourceIdentifier.Namespace,
+		Group:     &request.K8sRequest.ResourceIdentifier.GroupVersionKind.Group,
+		Version:   &request.K8sRequest.ResourceIdentifier.GroupVersionKind.Version,
+		Kind:      &request.K8sRequest.ResourceIdentifier.GroupVersionKind.Kind,
+	}
+	manifestRes, err := impl.helmAppService.GetDesiredManifest(ctx, request.AppIdentifier, resourceIdentifier)
```
Comment (pghildiyal) [inline pkg/k8s/K8sCommonService.go:97]: why are we using helmservice in k8scommonservice?

Comment (kartik-579) [reply pkg/k8s/K8sCommonService.go:97]: we are checking desired manifest before creating resource which is written in kubelink. Need to think about ways where we can use common methods like this without breaking architecture standards

Comment (Shivam-nagar23) [reply pkg/k8s/K8sCommonService.go]: It was used in case of external helm app when resource health goes missing, we were fetching desired manifest from kubelink to recreate resource, have refactored it to application service with appropriate name.

**Review by kartik-579 — APPROVED** [review]

**Review by kartik-579 — APPROVED** [review]
