### PR TITLE
fix:cve search 

### LINKED ISSUE #4361: Bug: CVE policy search breaking
### 📜 Description

If we search a CVE policy in security policies page, then the api gives error

### 👟 Reproduction steps

1) Go to security scan
2) Go to security policy and then search

### 👍 Expected behavior

Sarch showing result

### 👎 Actual Behavior

Search giving error

### ☸ Kubernetes version

NA

### Cloud provider

<details>
    NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

Bug fix

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7288

### PR DESCRIPTION
**Pull request by ShashwatDadhich**
# Description

Fix for CVE Policy search 

Fixes #4361

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] Does this PR requires documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

### CODE REVIEW

File: pkg/security/ImageScanService.go [hunk 1]
```diff
@@ -581,15 +581,17 @@ func (impl ImageScanServiceImpl) VulnerabilityExposure(request *security.Vulnera
 	cveStores = append(cveStores, cveStore)
 	for _, item := range vulnerabilityExposureList {
 		envId := 0
-		if item.AppStore {
+		if item.AppType == 1 {
```
Comment (gireesh-devtron) [inline pkg/security/ImageScanService.go:584]: use constants instead of hard coded values

File: pkg/security/ImageScanService.go [hunk 2]
```diff
@@ -581,15 +581,17 @@ func (impl ImageScanServiceImpl) VulnerabilityExposure(request *security.Vulnera
...
 			envId = item.ChartEnvId
-		} else {
+		} else if item.AppType == 0 {
```
Comment (gireesh-devtron) [inline pkg/security/ImageScanService.go:586]: same here

File: internal/sql/repository/security/CveStoreRepository.go [hunk 3]
```diff
@@ -51,7 +51,7 @@ type VulnerabilityExposure struct {
 	AppId   int    `json:"appId"`
 	EnvId   int    `json:"envId"`
 	//ClusterId     int    `json:"clusterId"`
-	AppStore      bool `json:"appStore"`
+	AppType       int  `json:"appType"`
```
Comment (gireesh-devtron) [inline internal/sql/repository/security/CveStoreRepository.go:54]: change the type appstore type

**Review by kripanshdevtron — APPROVED** [review]
