### PR TITLE
fix:  Unable to abort pre-cd and post-cd workflow

### LINKED ISSUE #4116: Bug: Unable to abort pre-cd and post-cd workflow
### 📜 Description

It bugs out when trying to abort a running pre-cd or post-cd pipeline. It throws an error : `can not find workflow <workflow-name>`

### 👟 Reproduction steps

1. Just configure a pre-cd or post-cd with a script : `tail -f /dev/null` to keep the pod running
2. Now try aborting the pipeline, it'll throw an error.  

### 👍 Expected behavior

It should have aborted the pipeline.

### 👎 Actual Behavior

It is failing to abort the pipeline.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6296

### PR DESCRIPTION
**Pull request by Ashish-devtron**
# Description

Fixes #4116 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by subhashish-devtron — DISMISSED** [review]

**Review by kripanshdevtron — APPROVED** [review]

File: pkg/pipeline/CdHandler.go [hunk 1]
```diff
@@ -118,6 +119,7 @@ type CdHandlerImpl struct {
 	k8sUtil                                *k8s.K8sUtil
 	workflowService                        WorkflowService
 	config                                 *CdConfig
+	restConfig                             *rest.Config
```
Comment (kripanshdevtron) [inline pkg/pipeline/CdHandler.go:122]: We should not do this.

**Review by kripanshdevtron — CHANGES_REQUESTED** [review]

**Review by kripanshdevtron — APPROVED** [review]
