### PR TITLE
fix: deployment strategy no visible in build and deploy page

### LINKED ISSUE #3327: Bug: deployment strategy missing in build and deploy page
### 📜 Description

image

### 👟 Reproduction steps

1) create any workflow with cd
2) observe the cd pipeline does not show deployment strategy

### 👍 Expected behavior

should be able to see deployment strategy on cd-pipeline

### 👎 Actual Behavior

not able to see deployment strategy on cd-pipeline

### ☸ Kubernetes version

k8s

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2877

### PR DESCRIPTION
**Pull request by gireesh-devtron**
# Description

Fixes #3327

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/pipeline/PipelineBuilder.go [hunk 1]
```diff
@@ -2733,8 +2733,51 @@ func (impl PipelineBuilderImpl) filterDeploymentTemplate(strategyKey string, pip
 	return pipelineStrategyJson, nil
 }
 
+func (impl PipelineBuilderImpl) getStrategiesMapping(dbPipelineIds []int) (map[int][]*chartConfig.PipelineStrategy, error) {
+	strategiesMapping := make(map[int][]*chartConfig.PipelineStrategy)
+	strategiesByPipelineIds, err := impl.pipelineConfigRepository.GetAllStrategyByPipelineIds(dbPipelineIds)
+	if err != nil && errors.IsNotFound(err) {
```
Comment (kripanshdevtron) [inline pkg/pipeline/PipelineBuilder.go:2739]: i think condition is wrong here for 'errors.IsNotFound(err)'

File: pkg/pipeline/PipelineBuilder.go [hunk 2]
```diff
@@ -2733,8 +2733,51 @@ func (impl PipelineBuilderImpl) filterDeploymentTemplate(strategyKey string, pip
...
+	}
+	var dbPipelineIds []int
+	for _, dbPipeline := range triggerViewCdPipelinesResp.Pipelines {
+		dbPipelineIds = append(dbPipelineIds, dbPipeline.Id)
+	}
+
+	//construct strategiesMapping to get all strategies against pipelineId
+	strategiesMapping, err := impl.getStrategiesMapping(dbPipelineIds)
+	if err != nil {
+		impl.logger.Errorw("error in getting strategiesMapping", "err", err)
```
Comment (kripanshdevtron) [inline pkg/pipeline/PipelineBuilder.go:2763]: logging not needed here, since u have logged all cases in private func

**Review by kripanshdevtron — APPROVED** [review]
