### PR TITLE
fix: port service mapping

### LINKED ISSUE #4025: Bug: issue with service URL and port numbers
### 📜 Description

1. On copying service URL from dashboard, it copies all the port numbers in the URL in comma separated way.

For example, if you try to copy service URL by clicking on copy button for 'kubewatch-devtroncd-1-service:80', it will copy 'kubewatch-devtroncd-1-service:80,80'.

Screenshot 2023-10-06 at 8 36 00 AM

copied: devtron-nats:4222,6222,8222,7777,7422,7522

Also, if you see, the copied URL doesn't the namespace included.

2.  Shows duplicate service URL.

Screenshot 2023-10-06 at 8 33 16 AM

3. Incomplete service URL if you click on (+ more) button. It does not include the namespace in the service URL.

Screenshot 2023-10-06 at 8 33 16 AM

### 👟 Reproduction steps

You can see this for any application that have a service.

### 👍 Expected behavior

Listed issues should not be there.

### 👎 Actual Behavior

It should copy the particular service URL, in correct format and the complete URL(including namespace).

### ☸ Kubernetes version

1.26

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5988

### PR DESCRIPTION
**Pull request by ashishdevtron**
# Description
These changes correctly maps port list with service names in case of helm deployed applications

Fixes #4025 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by vikramdevtron — DISMISSED** [review]

File: pkg/k8s/K8sCommonService.go [hunk 1]
```diff
@@ -496,15 +524,25 @@ func (impl K8sCommonServiceImpl) PortNumberExtraction(resp []BatchResourceRespon
 				impl.logger.Warnw("value not found in resourceTreeVal, unable to extract port no")
 				continue
 			}
+			serviceNameRes, ok := value[k8sCommonBean.K8sClusterResourceNameKey]
```
Comment (kartik-579) [inline pkg/k8s/K8sCommonService.go:527]: why are we checking K8sClusterResourceNameKey for service value?

**Review by vikramdevtron — APPROVED** [review]
