### PR TITLE
fix: Helm repository deleted from argocd-cm when deleted from UI (Github Issue #1399)

### LINKED ISSUE #1399: Helm repository doesn't get deleted from argocd-cm when deleted from UI.
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

If any of the helm-repository stops responding from server side or if we block access to it from our cluster, Argocd blocks all helm chart deployments until access to that repository is resolved

**To Reproduce**

1. Create a temporary helm repo and add it on Devtron and then remove the repo so that the repo doesn't exist anymore or block access to any existing helm repository url from cluster
2. Argocd will respond with errors if you deploy or update and deploy any helm chart from any repo
3. Delete the repo from Devtron UI

**Expected behavior**

The error from argocd should get resolved as we have already deleted the repository using Devtron

**Current behavior** 

It doesn't get resolved as argocd fetches repositories from argocd-cm and the repo after deleting from devtron still exists in argocd-cm and we have to delete it manually

AB#342

### PR DESCRIPTION
**Pull request by Ash-exp**
# Description

1. If any of the helm-repository stops responding from server side or if we block access to it from our cluster, Argocd blocks all helm chart deployments until access to that repository is resolved. Hence we also have to delete the repository from the Argocd config-map.

2. When updating a helm repository the repository name is not updated at the DB record and also the a new repository gets created at Argocd config-map instead of updating the previous one. Hence I modified the related functions accordingly.

Ticket [AB 342](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=342)
Fixes #1399 

## How Has This Been Tested?

1. - Create a temporary helm repo and add it on Devtron and then remove the repo so that the repo doesn't exist anymore or block access to any existing helm repository url from cluster
    - Argocd will respond with errors if you deploy or update and deploy any helm chart from any repo
    - Delete the repo from Devtron UI
    - The error from argocd should get resolved as we have already deleted the repository using Devtron
  
- [x] Tested Manually

2. - Create a temporary helm repo and add it on Devtron and then try to update only the repo name from UI
    - The updated name should reflect on UI and also the Argocd Config map should update the previous repo with the new name instead of creating a new entry with the updated name.
    
- [x] Tested Manually

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/chartRepo/ChartRepositoryService.go [hunk 1]
```diff
@@ -541,41 +627,159 @@ func (impl *ChartRepositoryServiceImpl) updateData(data map[string]string, reque
...
-	dbConnection := impl.repoRepository.GetConnection()
-	tx, err := dbConnection.Begin()
+// updateAndDeleteData update the request field in the argo-cm and delete the previous repo
+func (impl *ChartRepositoryServiceImpl) updateAndDeleteData(data map[string]string, request *ChartRepoDto, previousName string) map[string]string {
+	helmRepoStr := data["helm.repositories"]
+	helmRepoByte, err := yaml.YAMLToJSON([]byte(helmRepoStr))
 	if err != nil {
-		impl.logger.Errorw("error in establishing db connection, DeleteChartRepo", "err", err)
-		return err
+		panic(err)
```
Comment (iamayushm) [inline pkg/chartRepo/ChartRepositoryService.go:635]: Don't use panic in case of error. Log error with proper message and return it.

File: pkg/chartRepo/ChartRepositoryService.go [hunk 2]
```diff
@@ -541,41 +627,159 @@ func (impl *ChartRepositoryServiceImpl) updateData(data map[string]string, reque
...
+	data["dex.config"] = string([]byte(dexConfigStr))
+	return data
+}
+
+// deleteData delete the request field from the argo-cm
+func (impl *ChartRepositoryServiceImpl) deleteData(data map[string]string, request *ChartRepoDto) map[string]string {
+	helmRepoStr := data["helm.repositories"]
+	helmRepoByte, err := yaml.YAMLToJSON([]byte(helmRepoStr))
+	if err != nil {
+		panic(err)
```
Comment (pghildiyal) [inline pkg/chartRepo/ChartRepositoryService.go:722]: dont use panic

Comment (Ash-exp) [reply pkg/chartRepo/ChartRepositoryService.go]: Updated 👍

**Review by iamayushm — APPROVED** [review]

**Review by iamayushm — APPROVED** [review]
