### PR TITLE
fix: app update migration

### LINKED ISSUE #5914: Bug: duplicate app migration fix
### 📜 Description

duplicate entry for apps is created 

### 👟 Reproduction steps

NA

### 👍 Expected behavior

NA

### 👎 Actual Behavior

apps get deleted from DB 

### ☸ Kubernetes version

NA

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by iamayushm**
# Description

Fixes #5914

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/app/AppCrudOperationService.go [hunk 1]
```diff
@@ -463,10 +463,37 @@ func (impl AppCrudOperationServiceImpl) getAppAndProjectForAppIdentifier(appIden
...
+		allActiveApps, err := impl.appRepository.FindAllActiveByName(appNameUniqueIdentifier)
+		if err != nil {
+			impl.logger.Errorw("error in fetching all active apps by name", "appName", appNameUniqueIdentifier, "err", err)
+			return app, err
+		}
+		var validApp *appRepository.App
+		for _, activeApp := range allActiveApps {
+			if activeApp.Id != validAppId {
+				activeApp.Active = false
+				err := impl.appRepository.Update(activeApp)
```
Comment (nishant-d) [inline pkg/app/AppCrudOperationService.go:486]: log

File: pkg/app/AppCrudOperationService.go [hunk 2]
```diff
@@ -463,10 +463,37 @@ func (impl AppCrudOperationServiceImpl) getAppAndProjectForAppIdentifier(appIden
 	var err error
 	appNameUniqueIdentifier := appIdentifier.GetUniqueAppNameIdentifier()
 	app, err = impl.appRepository.FindAppAndProjectByAppName(appNameUniqueIdentifier)
-	if err != nil && err != pg.ErrNoRows {
+	if err != nil && err != pg.ErrNoRows && err != pg.ErrMultiRows {
 		impl.logger.Errorw("error in fetching app meta data by unique app identifier", "appNameUniqueIdentifier", appNameUniqueIdentifier, "err", err)
 		return app, err
 	}
+	if err == pg.ErrMultiRows {
```
Comment (nishant-d) [inline pkg/app/AppCrudOperationService.go:470]: extract as function

**Review by nishant-d — CHANGES_REQUESTED** [review]

**Review by vikramdevtron — APPROVED** [review]

**Review by nishant-d — APPROVED** [review]
