### PR TITLE
fix: SSO configuration gets change after refreshing the page

### LINKED ISSUE #3581: Bug: sso issuer issue in case of GitLab
### 📜 Description

1.when we are trying to configure sso with GitLab after entering the all the data  (like clientID,clientSecret ) when we click on save button all the configure are saved but the issuer is not saved . and by default its taking issuer as ***https://gitlab.com*** in backend 
2.if in the issuer section i give my self hosted gitlab and edit in the devtron-cm but also it's use the issuer as https://gitlab.com not the self hosted one.

### 👟 Reproduction steps

Just trying to install devtron and try sso with gitlab
Then also try the same with self hosted gitlab

### 👍 Expected behavior

Screenshot 2023-06-30 at 4 36 38 PM

### 👎 Actual Behavior

Screenshot 2023-06-30 at 4 33 13 PM

### ☸ Kubernetes version

EKS 1.26

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#4062

### PR DESCRIPTION
**Pull request by Ashish-devtron**
# Description

After saving any SSO configuration it's getting saved correctly, but after refreshing the page it shows some fixed values for all the SSO login services.

Fixes #3581 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested by adding and updating different sso config

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/sso/SSOLoginService.go [hunk 1]
```diff
@@ -179,15 +171,23 @@ func (impl SSOLoginServiceImpl) UpdateSSOLogin(request *bean.SSOLoginDto) (*bean
 	configString := string(configDataByte)
 	var configData Config
 	err = json.Unmarshal([]byte(configString), &configData)
+	if err != nil {
+		impl.logger.Debugw("error while Unmarshal", "error", err)
```
Comment (kripanshdevtron) [inline pkg/sso/SSOLoginService.go:175]: correct log Level here

**Review by kripanshdevtron — APPROVED** [review]
