### PR TITLE
fix: implemented cache for storing cloud provider 

### LINKED ISSUE #4594: Enhancement: reduce API calls to multiple IMDS server everytime any posthog event is sent
### 🔖 Feature description

Reduce the number of API calls made to IMDS server, when sending posthog events for fetching cloud provider.

### 🎤 Pitch / Usecases

.

### 🔄️ Alternative

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8226

### PR DESCRIPTION
**Pull request by ashishdevtron**
# Description

Fixes #4594 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: client/telemetry/TelemetryEventClient.go [hunk 1]
```diff
@@ -58,6 +58,7 @@ type TelemetryEventClientImpl struct {
 	InstalledAppRepository         repository2.InstalledAppRepository
 	userAttributesRepository       repository.UserAttributesRepository
 	cloudProviderIdentifierService cloudProviderIdentifier.ProviderIdentifierService
+	cloudProviderCache             string
```
Comment (kartik-579) [inline client/telemetry/TelemetryEventClient.go:61]: move this in a common config which can be used in future as well for similar cases

File: client/telemetry/TelemetryEventClient.go [hunk 2]
```diff
@@ -105,9 +106,24 @@ func NewTelemetryEventClientImpl(logger *zap.SugaredLogger, client *http.Client,
 		logger.Errorw("error in starting heartbeat event", "err", err)
 		return nil, err
 	}
+	err = watcher.UpdateCloudProviderCache()
+	if err != nil {
+		logger.Errorw("error in updating cloud provider", "err", err)
+		return nil, err
+	}
```
Comment (kartik-579) [inline client/telemetry/TelemetryEventClient.go:113]: this will slow startup, instead lets do this for all calls of getting identifyProvider where we first check if this has been set and if not then call the process

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by nishant-d — APPROVED** [review]
