### PR TITLE
Ingress Urls User level access Issue

### LINKED ISSUE #2660: Bug: Urls API is not showing urls even user can see them in the manifests
### 📜 Description

If user can see the manifests of service and ingress he must be able to get urls if exists.But we are getting user don't have access response.

### 👟 Reproduction steps

1. login as a non super admin user.
2. Go to app details page,click on urls tab.

### 👍 Expected behavior

user should be shown urls if exists or show no urls found message.

### 👎 Actual Behavior

user is getting no access response,even user has access to the manifests.

### ☸ Kubernetes version

1.22

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by gireesh-devtron**
# Description
Fixed the access denied issue while fetching urls of service and manifest for non super-admins.

Fixes #2660
## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
test-cases
- [x] Tested for non-super admin users 

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: api/restHandler/AppListingRestHandler.go [hunk 1]
```diff
@@ -587,6 +587,20 @@ func (handler AppListingRestHandlerImpl) GetHostUrlsByBatch(w http.ResponseWrite
 		common.WriteJsonResp(w, fmt.Errorf("only one of the appId or installedAppId should be valid appId: %s installedAppId: %s", appIdParam, installedAppIdParam), nil, http.StatusBadRequest)
 		return
 	}
+	token := r.Header.Get("token")
+	if appIdParam != "" {
+		appId, err := strconv.Atoi(appIdParam)
+		if err != nil {
+			handler.logger.Errorw("error in parsing appId from request body", "appId", appIdParam, "err", err)
+			common.WriteJsonResp(w, fmt.Errorf("error in parsing appId : %s must be integer", envIdParam), nil, http.StatusBadRequest)
```
Comment (kripanshdevtron) [inline api/restHandler/AppListingRestHandler.go:595]: use appIdParam instead of envIdParam

File: api/restHandler/AppListingRestHandler.go [hunk 2]
```diff
@@ -610,11 +624,19 @@ func (handler AppListingRestHandlerImpl) GetHostUrlsByBatch(w http.ResponseWrite
...
-		return
+	if installedAppIdParam != "" {
+		object, object2 := handler.enforcerUtil.GetHelmObjectByAppNameAndEnvId(appDetail.AppName, appDetail.EnvironmentId)
+		ok := handler.enforcer.Enforce(token, casbin.ResourceHelmApp, casbin.ActionGet, object) || handler.enforcer.Enforce(token, casbin.ResourceHelmApp, casbin.ActionGet, object2)
+		if !ok {
+			common.WriteJsonResp(w, fmt.Errorf("unauthorized user"), nil, http.StatusForbidden)
+			return
+		}
+	} else {
+		object := handler.enforcerUtil.GetAppRBACNameByAppId(appId)
```
Comment (kripanshdevtron) [inline api/restHandler/AppListingRestHandler.go:635]: do we still need to check again??

**Review by kripanshdevtron — APPROVED** [review]
