### PR TITLE
fix:  app status fix for helm apps which are deployed via acd

### LINKED ISSUE #3485: Bug: Scale workload status not showing for helm chart
### 📜 Description

Scale workload status (deployment status and app status) not showing for helm chart which is deployed with argocd .

### 👟 Reproduction steps

1.Click on chart store
2.Deploy any helm chart which is deployed with argocd
3.click on scale workload 
3.check app status and deployment status

### 👍 Expected behavior

While we scale workload app status should be in hibernating and deployment status should be healthy

### 👎 Actual Behavior

While we scaling workload app status healthy and deployment status  healthy showing.

### ☸ Kubernetes version

AKS : 1.26

### Cloud provider

Azure

### 🌍 Browser

Chrome

### 🧱 Your Environment

QA

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ShashwatDadhich**
# Description
 
Scale workload status (deployment status and app status) not showing for helm chart which is deployed with argocd

Fixes #3485

## How Has This Been Tested?

- [x] Test Locally
- [x] Test by deploying it in VM

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

### CODE REVIEW

**Review by gireesh-devtron — DISMISSED** [review]
LGTM

File: pkg/appStore/deployment/service/InstalledAppService.go [hunk 1]
```diff
@@ -1298,6 +1305,12 @@ func (impl InstalledAppServiceImpl) fetchResourceTreeForACD(rctx context.Context
 	}
 	// TODO: using this resp.Status to update in app_status table
 	resourceTree = util3.InterfaceToMapAdapter(resp)
+	resourceTree, status := impl.checkHibernate(resourceTree, deploymentAppName, ctx)
```
Comment (gireesh-devtron) [inline pkg/appStore/deployment/service/InstalledAppService.go:1308]: change ``status``  to ``isHibernating``

Comment (ShashwatDadhich) [reply pkg/appStore/deployment/service/InstalledAppService.go]: done

**Review by gireesh-devtron — APPROVED** [review]

**Review by gireesh-devtron — APPROVED** [review]

**Review by kripanshdevtron — APPROVED** [review]

**Review by kripanshdevtron — APPROVED** [review]
