### PR TITLE
fix: latest version in default cluster and on UI

### LINKED ISSUE #5246: Bug: Chart sync marking first chart version as latest
### 📜 Description

Chart sync Job is marking the first chart as latest. Chart store is showing first version of all the charts fetched by chart sync. This is also failing the devtron agent install button as that is also installing the first version of rollout chart (marked latest) in the cluster.

### Affected areas

Deployment from Chart store

### Additional affected areas

Other NON-CRITICAL functionality

### Prod/Non-prod environments?

Prod

### Is User unblocked?

Yes

### How was the user un-blocked?

PERMANENTLY - By giving a workaround (Within Devtron)

### Impact on Enterprise

Users are not able to see latest chart version from chart store, however opening an individual chart shows the latest version

### 👟 Steps to replicate the Issue

Install v0.6.29 devtron version from OSS

### 👍 Expected behavior

It should show latest version as latest for a chart instead of first version

### 👎 Actual Behavior

It's showing first version of chart as latest

### ☸ Kubernetes version

microk8s 1.29

### Cloud provider

<details>
NA
</details>

### 🌍 Browser

Chrome

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9921

### PR DESCRIPTION
**Pull request by iamayushm**
# Description

Fixes #5246 

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by gireesh-devtron — APPROVED** [review]
LGTM

File: pkg/appStore/chartGroup/ChartGroupService.go [hunk 1]
```diff
@@ -773,11 +775,25 @@ func (impl *ChartGroupServiceImpl) DeployDefaultChartOnCluster(bean *cluster2.Cl
...
 			for _, item := range charts.ChartComponent {
-				appStoreApplicationVersionId, err := impl.appStoreApplicationVersionRepository.FindLatestAppStoreVersionIdByAppStoreName(item.Name)
+				appStore, err := impl.appStoreRepository.FindAppStoreByName(item.Name)
 				if err != nil {
-					impl.logger.Errorw("DeployDefaultChartOnCluster, error in getting app store", "data", t, "err", err)
+					impl.logger.Errorw("error in getting app store by name", "appStoreName", item.Name, "err", err)
 					return false, err
 				}
+				var appStoreApplicationVersionId int
+				if len(appStore.DockerArtifactStoreId) > 0 {
```
Comment (gireesh-devtron) [inline pkg/appStore/chartGroup/ChartGroupService.go:784]: can we define a variable like isOCIRepo := `len(appStore.DockerArtifactStoreId) > 0`

**Review by nishant-d — APPROVED** [review]
