### PR TITLE
fix: duplicate role-group-fix

### LINKED ISSUE #3772: Bug: Devtron allows saving permission group with same name
### 📜 Description

Permission groups with exactly same name and different permissions can be created. Looks like validation is not handled at frontend and backend both. The bigger problem will occur when you want to associate the permission group with a user. UI shows the permission group as saved but on refreshing the page it gets reverted.  

The user is also unable to retain the permission group even after deleting and recreating the permission group with same name.

### 👟 Reproduction steps

- create 2 permission groups with same name.
- associate / add that permission group with any user and save.
- refresh the page and check if permission group is added.

### 👍 Expected behavior

We should not allow creating permission groups with same name. 

### 👎 Actual Behavior

We allow creating permission groups with same name.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

NA

### ✅ Proposed Solution

NA

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#5013

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Fixes #3772 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/user/repository/RoleGroupRepository.go [hunk 1]
```diff
@@ -123,6 +123,11 @@ func (impl RoleGroupRepositoryImpl) GetRoleGroupListByCasbinNames(names []string
 	err := impl.dbConnection.Model(&model).Where("casbin_name in (?)", pg.In(names)).Where("active = ?", true).Select()
 	return model, err
 }
+func (impl RoleGroupRepositoryImpl) GetRoleGroupByCasbinName(name string) (*RoleGroup, error) {
+	var model RoleGroup
+	err := impl.dbConnection.Model(&model).Where("casbin_name = ?", name).Where("active = ?", true).Order("updated_on desc").Select()
```
Comment (kartik-579) [inline pkg/user/repository/RoleGroupRepository.go:128]: what is the need of ordering? if there can be multiple rows in output use limit with this or use slice model

File: pkg/user/RoleGroupService.go [hunk 2]
```diff
@@ -85,19 +85,26 @@ func (impl RoleGroupServiceImpl) CreateRoleGroup(request *bean.RoleGroup) (*bean
...
 		//create new user in our db on d basis of info got from google api or hex. assign a basic role
+
 		model := &repository2.RoleGroup{
 			Name:        request.Name,
 			Description: request.Description,
 		}
 		rgName := strings.ToLower(request.Name)
 		object := "group:" + strings.ReplaceAll(rgName, " ", "_")
+
+		_, err := impl.roleGroupRepository.GetRoleGroupByCasbinName(object)
```
Comment (kartik-579) [inline pkg/user/RoleGroupService.go:96]: are we only using this for checking if entry exists or not? if yes then we should use exists clause since this is confusing. Also, add comments

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: pkg/user/RoleGroupService.go [hunk 3]
```diff
@@ -94,11 +94,11 @@ func (impl RoleGroupServiceImpl) CreateRoleGroup(request *bean.RoleGroup) (*bean
...
 		object := "group:" + strings.ReplaceAll(rgName, " ", "_")
 
-		roleGroup, err := impl.roleGroupRepository.GetRoleGroupByCasbinName(object)
+		exists, err := impl.roleGroupRepository.CheckRoleGroupExistByCasbinName(object)
 		if err != nil && err != pg.ErrNoRows {
 			impl.logger.Errorw("error in getting role group by casbin name", "err", err, "casbinName", object)
 			return nil, err
-		} else if roleGroup != nil {
+		} else if exists {
 			impl.logger.Errorw("role group already present", "err", err)
```
Comment (kartik-579) [inline pkg/user/RoleGroupService.go:101]: add roleGroup name for debugging

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by kartik-579 — APPROVED** [review]

**Comment by prakarsh-dt** [comment]
@Shivam-nagar23 @kartik-579 @vikramdevtron What is the blocker here? Why are we not merging this?
