### PR TITLE
fix: containers are missing from app-details page in argocd app 

### LINKED ISSUE #4944: Bug: Containers is missing from app-details page
### 📜 Description

We have 2 containers in a pod, but we weren't able to view logs and other details of the sidecar container which got injected in the pod at runtime, for example: istio envoy-proxy. 

Screenshot 2024-04-15 at 6 53 03 PM

Here, the istio envoy-proxy container is missing in app-details page

### 👟 Reproduction steps

Try to inject the additional container in the pod-like an istio envoy-proxy and we can see the container is missing in the app-details page. 

### 👍 Expected behavior

We should get the details of all the pods in the app-details page. 

### 👎 Actual Behavior

All containers are missing in app-details page

### ☸ Kubernetes version

EKS 1.29

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9352

### PR DESCRIPTION
**Pull request by ShashwatDadhich**
# Description

Containers is missing from app-details page.

Fixes #4944

## How Has This Been Tested?

- [x] Tested locally 
- [x] Tested by deploying in VM.

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] Does this PR requires documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.](fix: dependabot version upgrade)

### CODE REVIEW

File: client/argocdServer/application/Application.go [hunk 1]
```diff
@@ -331,19 +331,55 @@ func (c ServiceClientImpl) buildPodMetadata(resp *v1alpha1.ApplicationTree, resp
...
 		}
+		duplicatePodToReplicasetMapping = duplicateMapping
 	}
+
 	if newPodNames != nil {
-		results := buildPodMetadataFromPod(resp, podManifests, newPodNames)
-		for _, meta := range results {
-			if _, ok := duplicateCheck[meta.Name]; !ok {
-				podMetaData = append(podMetaData, meta)
+		podsMetadataFromPods := buildPodMetadataFromPod(resp, podManifests, newPodNames)
```
Comment (nishant-d) [inline client/argocdServer/application/Application.go:344]: extract this as separate function

**Review by nishant-d — CHANGES_REQUESTED** [review]

**Review by prakash100198 — APPROVED** [review]

**Review by nishant-d — APPROVED** [review]
