### PR TITLE
fix: app-group page breaking for inactive users

### LINKED ISSUE #4316: Bug: Overview Page in Application group breaking
### 📜 Description

For some environments overview page in application group is breaking 
Screenshot 2023-11-30 at 12 22 25 PM

### 👟 Reproduction steps

None

### 👍 Expected behavior

It should show the application deployed in that environment 

### 👎 Actual Behavior

Overview Page is breaking

### ☸ Kubernetes version

1.25

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ashishdevtron**
# Description

fixes the issue where page breaks in app group when opening an environment of user which is already deleted 

Fixes #4316 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/app/AppListingService.go [hunk 1]
```diff
@@ -242,18 +243,27 @@ func (impl AppListingServiceImpl) FetchOverviewAppsByEnvironment(envId, limit, o
 		resp.Type = NonProduction
 	}
 	resp.Description = env.Description
-	createdBy, err := impl.userRepository.GetById(env.CreatedBy)
-	if err != nil {
-		return resp, err
+	createdBy, err := impl.userRepository.GetByIdIncludeDeleted(env.CreatedBy)
+	if err != nil && err != pg.ErrNoRows {
+		impl.Logger.Errorw("error in fetching user for app meta info", "error", err)
```
Comment (kartik-579) [inline pkg/app/AppListingService.go:248]: log createdBy param

File: internal/sql/repository/AppListingRepository.go [hunk 2]
```diff
@@ -147,7 +147,12 @@ func (impl AppListingRepositoryImpl) FetchOverviewAppsByEnvironment(envId, limit
 
 func (impl AppListingRepositoryImpl) FetchLastDeployedImage(appId, envId int) (*LastDeployed, error) {
 	var lastDeployed []*LastDeployed
-	query := `select ca.image as last_deployed_image, u.email_id as last_deployed_by from pipeline p
+	query := `select ca.image as last_deployed_image, 
+			    case
+					when u.active = false then u.email_id || ' (inactive)'
```
Comment (kartik-579) [inline internal/sql/repository/AppListingRepository.go:152]: add comment in code why we are doing this

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by kartik-579 — APPROVED** [review]

File: pkg/app/AppListingService.go [hunk 3]
```diff
@@ -242,18 +243,27 @@ func (impl AppListingServiceImpl) FetchOverviewAppsByEnvironment(envId, limit, o
...
-	resp.CreatedBy = createdBy.EmailId
 	envContainers, err := impl.appListingRepository.FetchOverviewAppsByEnvironment(envId, limit, offset)
 	if err != nil {
+		impl.Logger.Errorw("failed to fetch environment containers", "err", err, "env id", envId)
 		return resp, err
 	}
 	for _, envContainer := range envContainers {
 		lastDeployed, err := impl.appListingRepository.FetchLastDeployedImage(envContainer.AppId, envId)
 		if err != nil {
+			impl.Logger.Errorw("failed to fetch last deployed image", "err", err, "app id", envContainer.AppId, "env id", envId)
```
Comment (kripanshdevtron) [inline pkg/app/AppListingService.go:266]: Please use camelCase for param keys like `appId` instead of `app id`

**Review by kripanshdevtron — APPROVED** [review]
