### PR TITLE
fix: app metrics dynamically enabled based on support

### LINKED ISSUE #3303: Bug: Not able to enable app metrics for deployment charts
### 📜 Description

For the application with deployment charts not able to enable app metrics.

### 👟 Reproduction steps

1. Create a new application with deployment-type charts.
2. Try to enable app metrics with the checkbox.

### 👍 Expected behavior

It should enable the app metrics for the respective application. It's not updating the database too.

### 👎 Actual Behavior

Not able to enable this feature now.

### ☸ Kubernetes version

EKS 1.21

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#2820

### PR DESCRIPTION
**Pull request by Ash-exp**
# Description

Made App Metrics Flag dynamic with respect to the deployment chart's compatibility to support application metrics. For this I used the data in orchestrator `chart_ref.is_app_metrics_supported` as a flag to apply App Metrics request.

Ticket : [AB 2820](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2820)
Fixes #3303 #3413

## How Has This Been Tested?
[Test Coverage Link](https://docs.google.com/spreadsheets/d/1kdk8MOY4oDD3Za-2yBih0rLukXLx8SeLpNFgR5yLlsg/edit?usp=sharing)
- [x] Base Deployment Template
- [x] Create Environment Override
- [x] Update Environment Override

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/pipeline/PropertiesConfig.go [hunk 1]
```diff
@@ -277,17 +279,20 @@ func (impl PropertiesConfigServiceImpl) CreateEnvironmentProperties(appId int, e
...
+	if err != nil {
+		impl.logger.Errorw("error in finding ref chart by id", "err", err)
+		return nil, err
+	}
+	if !(chartRefValue.IsAppMetricsSupported) {
 		appMetricsRequest := chartService.AppMetricEnableDisableRequest{UserId: environmentProperties.UserId, AppId: appId, EnvironmentId: environmentProperties.EnvironmentId, IsAppMetricsEnabled: false}
 		_, err = impl.EnvMetricsEnableDisable(&appMetricsRequest)
 		if err != nil {
-			impl.logger.Errorw("err while disable app metrics for lower versions", "err", err, "appId", appId, "chartMajorVersion", chartMajorVersion, "chartMinorVersion", chartMinorVersion)
+			impl.logger.Errorw("err while disable app metrics for lower versions", "err", err, "appId", appId, "chartVersion", chart.ChartVersion)
```
Comment (prakash100198) [inline pkg/pipeline/PropertiesConfig.go:295]: change error message, you can remove lower versions.

**Review by prakash100198 — APPROVED** [review]

File: pkg/pipeline/PropertiesConfig.go (hunk 1 above)
Comment (Ash-exp) [reply pkg/pipeline/PropertiesConfig.go:295]: Implemented 👍

**Review by prakash100198 — APPROVED** [review]

**Review by vikramdevtron — APPROVED** [review]
