### PR TITLE
fix: prevented chart updation when its in use

### LINKED ISSUE #3455: Bug: data validation error when we disable/enable a chart repo
### 📜 Description

Getting a data validation error when we disable/enable a chart repository where charts from this repository is already used to deploy a existing helm app

### 👟 Reproduction steps

1.Global Configurations ->Chart Repositories
2.chose a chart repository where charts from this repository is already deployed in a helm app

### 👍 Expected behavior

it should not allow to enable/disable such chart repositories like it is in the case of edit repository
issue1

### 👎 Actual Behavior

right now we can enable/disable such chart repo leading to unwanted data validation toast message.
issue3

### ☸ Kubernetes version

AKS 1.24

### Cloud provider

<details>
Azure
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

Automation/Staging
### ✅ Proposed Solution

remove auth mode validation
issue2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3426

### PR DESCRIPTION
**Pull request by ashishdevtron**
# Description
Chart repo which is used to deploy helm app can be updated through postman, which should not happen.

Fixes #3455

## How Has This Been Tested?

- [x] Tested locally

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

```release-note

```

### CODE REVIEW

File: pkg/chartRepo/repository/ChartRepoRepository.go [hunk 1]
```diff
@@ -123,6 +125,22 @@ func (impl ChartRepoRepositoryImpl) FindAllWithDeploymentCount() ([]*ChartRepoWi
...
+	query := "select count(jq.ia_id ) as deployment_count" +
+		" from chart_repo left join" +
+		" (select aps.chart_repo_id as cr_id ,ia.id as ia_id from installed_app_versions iav" +
+		" inner join installed_apps ia on iav.installed_app_id = ia.id" +
+		" inner join app_store_application_version asav on iav.app_store_application_version_id = asav.id" +
+		" inner join app_store aps on asav.app_store_id = aps.id" +
+		" where ia.active=true and iav.active=true) jq" +
+		" on jq.cr_id = chart_repo.id" +
+		" where chart_repo.deleted = false and chart_repo.id = " + strconv.Itoa(chartId) +
+		" Group by chart_repo.id;"
```
Comment (kartik-579) [inline pkg/chartRepo/repository/ChartRepoRepository.go:139]: can remove this

File: pkg/chartRepo/repository/ChartRepoRepository.go [hunk 2]
```diff
@@ -123,6 +125,22 @@ func (impl ChartRepoRepositoryImpl) FindAllWithDeploymentCount() ([]*ChartRepoWi
 	return repo, err
 }
 
+func (impl ChartRepoRepositoryImpl) FindDeploymentCountByChartRepoId(chartId int) (int, error) {
+	var activeDeploymentCount int
+	query := "select count(jq.ia_id ) as deployment_count" +
+		" from chart_repo left join" +
+		" (select aps.chart_repo_id as cr_id ,ia.id as ia_id from installed_app_versions iav" +
```
Comment (kartik-579) [inline pkg/chartRepo/repository/ChartRepoRepository.go:132]: we can only make this work by only executing the subquery and putting the id where clause there only

File: api/chartRepo/ChartRepositoryRestHandler.go [hunk 3]
```diff
@@ -213,7 +213,17 @@ func (handler *ChartRepositoryRestHandlerImpl) UpdateChartRepo(w http.ResponseWr
 		common.WriteJsonResp(w, err, nil, http.StatusBadRequest)
 		return
 	}
-
+	activeDeployment, err := handler.chartRepositoryService.CheckDeploymentCount(request)
+	if err != nil {
+		if activeDeployment > 0 {
```
Comment (kartik-579) [inline api/chartRepo/ChartRepositoryRestHandler.go:218]: we can move this to service layer only to avoid logic in handler

File: pkg/chartRepo/ChartRepositoryService.go [hunk 4]
```diff
@@ -211,6 +212,18 @@ func (impl *ChartRepositoryServiceImpl) CreateChartRepo(request *ChartRepoDto) (
 	return chartRepo, nil
 }
 
+func (impl *ChartRepositoryServiceImpl) CheckDeploymentCount(request *ChartRepoDto) (int, error) {
```
Comment (kartik-579) [inline pkg/chartRepo/ChartRepositoryService.go:215]: maybe we can rename this to ValidateDeploymentCount or something similar

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: pkg/chartRepo/repository/ChartRepoRepository.go [hunk 5]
```diff
@@ -123,6 +125,19 @@ func (impl ChartRepoRepositoryImpl) FindAllWithDeploymentCount() ([]*ChartRepoWi
...
 }
 
+func (impl ChartRepoRepositoryImpl) FindDeploymentCountByChartRepoId(chartId int) (int, error) {
+	var activeDeploymentCount int
+	query := "select count(aps.chart_repo_id) as deployment_count " +
+		" from installed_app_versions iav" +
+		" inner join installed_apps ia on iav.installed_app_id = ia.id" +
+		" inner join app_store_application_version asav on iav.app_store_application_version_id = asav.id" +
+		" inner join app_store aps on asav.app_store_id = aps.id" +
+		" where ia.active=true and iav.active=true and aps.chart_repo_id = " + strconv.Itoa(chartId) +
```
Comment (kartik-579) [inline pkg/chartRepo/repository/ChartRepoRepository.go:135]: let's extract the input parameters out for better debuggability

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by kartik-579 — APPROVED** [review]

File: api/chartRepo/ChartRepositoryRestHandler.go [hunk 6]
```diff
@@ -213,7 +213,12 @@ func (handler *ChartRepositoryRestHandlerImpl) UpdateChartRepo(w http.ResponseWr
 		common.WriteJsonResp(w, err, nil, http.StatusBadRequest)
 		return
 	}
-
+	err = handler.chartRepositoryService.ValidateDeploymentCount(request)
```
Comment (nishant-d) [inline api/chartRepo/ChartRepositoryRestHandler.go:216]: we can put this validation after RBAC
