### PR TITLE
fix: build-context-git-material is not being set for cloned apps

### LINKED ISSUE #3398: Bug: Build configurations page and CI pipeline in workflow editor is breaking for cloned apps
### 📜 Description

It bugs when you create an application using `clone existing application`.
Build configurations page and CI pipeline in workflow editor is breaking.

### 👟 Reproduction steps

Create an application using `clone existing application`.

### 👍 Expected behavior

App should have cloned and configured properly.

### 👎 Actual Behavior

Cloned App is breaking at build configuration and CI pipeline in workflow editor.

### ☸ Kubernetes version

EKS 1.24

### Cloud provider

AWS

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3099

### PR DESCRIPTION
**Pull request by gireesh-devtron**
# Description

Fixes #3398

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/appClone/AppCloneService.go [hunk 1]
```diff
@@ -278,10 +278,13 @@ func (impl *AppCloneServiceImpl) CreateCiTemplate(oldAppId, newAppId int, userId
 		return nil, fmt.Errorf("no git for %d", newAppId)
 	}
 	dockerfileGitMaterial := 0
+	buildContextGitMaterial := 0
 	if len(gitMaterials) == 1 {
 		dockerfileGitMaterial = gitMaterials[0].Id
+		buildContextGitMaterial = gitMaterials[0].Id
```
Comment (kripanshdevtron) [inline pkg/appClone/AppCloneService.go:284]: reuse vars here

File: pkg/appClone/AppCloneService.go [hunk 2]
```diff
@@ -278,10 +278,13 @@ func (impl *AppCloneServiceImpl) CreateCiTemplate(oldAppId, newAppId int, userId
...
 	} else {
 		refGitmaterial, err := impl.materialRepository.FindById(refCiConf.CiBuildConfig.GitMaterialId)
+		refBuildContextGitMaterial, err := impl.materialRepository.FindById(refCiConf.CiBuildConfig.BuildContextGitMaterialId)
```
Comment (kripanshdevtron) [inline pkg/appClone/AppCloneService.go:287]: compare `refCiConf.CiBuildConfig.BuildContextGitMaterialId` with `refCiConf.CiBuildConfig.GitMaterialId` if same then we can avoid db call.

**Review by kripanshdevtron — APPROVED** [review]
