### PR TITLE
fix: grpc error handling for TemplateChart req

### LINKED ISSUE #5009: Bug: 5xx error in TemplateChart request
### 📜 Description

when user enters wrong values in yaml (for eg: enters string values when array is expected) then it throws 5xx error

### 👟 Reproduction steps

enter wrong type in yaml

enter string in `image:` field

### 👍 Expected behavior

should throw 4xx error

### 👎 Actual Behavior

throws 5xx

### ☸ Kubernetes version

.

### Cloud provider

<details>
.
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9590

### PR DESCRIPTION
**Pull request by ashishdevtron**
# Description

Fixes #5009

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: api/helm-app/service/HelmAppService.go [hunk 1]
```diff
@@ -979,6 +982,13 @@ func (impl *HelmAppServiceImpl) GetNotes(ctx context.Context, request *gRPC.Inst
 	response, err := impl.helmAppClient.GetNotes(ctx, request)
 	if err != nil {
 		impl.logger.Errorw("error in fetching chart", "err", err)
+		clientErrCode, errMsg := util.GetClientDetailedError(err)
+		if clientErrCode.IsFailedPreconditionCode() {
+			return notesTxt, &util.ApiError{HttpStatusCode: http.StatusUnprocessableEntity, Code: strconv.Itoa(http.StatusUnprocessableEntity), InternalMessage: errMsg, UserMessage: errMsg}
+		}
+		if clientErrCode.IsInvalidArgumentCode() {
+			return notesTxt, &util.ApiError{HttpStatusCode: http.StatusConflict, Code: strconv.Itoa(http.StatusConflict), InternalMessage: errMsg, UserMessage: errMsg}
```
Comment (iamayushm) [inline api/helm-app/service/HelmAppService.go:990]: please review once

**Review by nishant-d — APPROVED** [review]
