### PR TITLE
fix: Artifacts filter in CD trigger view

### LINKED ISSUE #4063: Bug: restricted Images visible in CD trigger view
### 📜 Description

Expectation -> only images passed through pre-cd steps should be available in deploy stage
Bug -> all artifacts are available in deployment stage

### 👟 Reproduction steps

1) configure ci-pipeline
2) Trigger build
3) configure cd pipeline with pre and post cd enabled (keep trigger type = Manual as it will be easy to replicate)
4) all artifacts are available in deploy stage irrespective of it's deployment status in PRE-CD
5) add new CD in series with previous CD. All artifacts visible in it's parent post CD will be visible in it irrespective of deployment in it's parent post CD.

### 👍 Expected behavior

Only artifacts passed through pre-cd should be visible in deploy stage
Only artifacts passed through parent post cd should be visible in deploy stage.

### 👎 Actual Behavior

All Artifacts are visible in cd (deploy) stage

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6123

### PR DESCRIPTION
**Pull request by iamayushm**
# Description

Fixes following two issues:-
If CD parent is PRE-CD, Artifacts not deployed in PRE-CD are available in cd stage
If CD parent is POST-CD of another pipeline Artifacts not deployed in POST-CD are available for deployment in CD.
Fixes #4063 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Configured CD without PRE-CD : all Artifacts should come in this case
- [x] Configured CD with PRE-CD: only Artifacts deployed at PRE step should be available for deployment

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/pipeline/BuildPipelineConfigService.go [hunk 1]
```diff
@@ -1792,10 +1793,17 @@ func (impl *PipelineBuilderImpl) RetrieveArtifactsByCDPipeline(pipeline *pipelin
 		parentCdId = parentId
 	}
 
-	if stage == bean2.CD_WORKFLOW_TYPE_DEPLOY && len(pipeline.PreStageConfig) > 0 {
-		// Parent type will be PRE for DEPLOY stage
-		parentId = pipeline.Id
-		parentType = bean2.CD_WORKFLOW_TYPE_PRE
+	if stage == bean2.CD_WORKFLOW_TYPE_DEPLOY {
+		pipelineStage, err := impl.pipelineStageRepository.GetCdStageByCdPipelineIdAndStageType(pipeline.Id, repository3.PIPELINE_STAGE_TYPE_PRE_CD)
```
Comment (kartik-579) [inline pkg/pipeline/BuildPipelineConfigService.go:1797]: do the same thing if parent is POST_CD, needs to be updated in RetrieveParentDetails

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: pkg/pipeline/BuildPipelineConfigService.go [hunk 2]
```diff
@@ -1792,10 +1793,17 @@ func (impl *PipelineBuilderImpl) RetrieveArtifactsByCDPipeline(pipeline *pipelin
...
-		// Parent type will be PRE for DEPLOY stage
-		parentId = pipeline.Id
-		parentType = bean2.CD_WORKFLOW_TYPE_PRE
+	if stage == bean2.CD_WORKFLOW_TYPE_DEPLOY {
+		pipelinePreStage, err := impl.pipelineStageRepository.GetCdStageByCdPipelineIdAndStageType(pipeline.Id, repository3.PIPELINE_STAGE_TYPE_PRE_CD)
+		if err != nil && err != pg.ErrNoRows {
+			impl.logger.Errorw("error in fetching PRE-CD stage by cd pipeline id", "pipelineId", pipeline.Id, "err", err)
+			return nil, err
+		}
+		if pipelinePreStage != nil || len(pipeline.PreStageConfig) > 0 {
```
Comment (kartik-579) [inline pkg/pipeline/BuildPipelineConfigService.go:1802]: GetCdStageByCdPipelineIdAndStageType will always give  pipelinePreStage as not nill. Need to add check for pipelinePreStage.Id > 0 to be completely sure.

File: pkg/pipeline/DeploymentPipelineConfigService.go [hunk 3]
```diff
@@ -932,10 +938,10 @@ func (impl *PipelineBuilderImpl) RetrieveParentDetails(pipelineId int) (parentId
 			return 0, "", err
 		}
 
-		if len(parentPipeline.PostStageConfig) == 0 {
-			return workflow.ParentId, bean2.CD_WORKFLOW_TYPE_DEPLOY, nil
+		if len(parentPipeline.PostStageConfig) > 0 || parentPostStage != nil {
```
Comment (kartik-579) [inline pkg/pipeline/DeploymentPipelineConfigService.go:941]: id check here as well

**Review by kartik-579 — CHANGES_REQUESTED** [review]

**Review by kartik-579 — DISMISSED** [review]

**Review by vikramdevtron — APPROVED** [review]
