### PR TITLE
fix: shows commit details only on currently deployed image on deployment history

### LINKED ISSUE #3091: Bug: shows commit details only on currently deployed image on deployment history
### 📜 Description

shows commit details only on currently deployed image on deployment history.

### 👟 Reproduction steps

1. Open any application.
2. Go to deployment history.
3. Hover on latest image and then on other images deployed.
4. You'll get commit details on latest deployment only.

### 👍 Expected behavior

Should show the commit details for all the images deployed.

### 👎 Actual Behavior

showing commit details only on currently deployed image on deployment history.

### ☸ Kubernetes version

1.21

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Ashish-devtron**
# Description
Currently, shows commit details only on currently deployed image on deployment history.
Expected, Should show the commit details for all the images deployed.

Fixes #3091 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] Tested by Deploying image multiple times for both Helm and GitOps

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/pipeline/CdHandler.go [hunk 1]
```diff
@@ -715,6 +715,55 @@ func (impl *CdHandlerImpl) GetCdBuildHistory(appId int, environmentId int, pipel
...
+
+		var ciArtifactIds []int
+		for _, cdWfA := range cdWorkflowArtifact {
+			ciArtifactIds = append(ciArtifactIds, cdWfA.CiArtifactId)
+		}
+		ciWfs, err := impl.ciWorkflowRepository.FindAllLastTriggeredWorkflowByArtifactId(ciArtifactIds)
+		if err != nil && err != pg.ErrNoRows {
+			impl.Logger.Errorw("error in fetching ci wfs", "artifactIds", ciArtifactIds, "err", err)
+			return cdWorkflowArtifact, err
+		}
```
Comment (prakash100198) [inline pkg/pipeline/CdHandler.go:728]: Handle error when error will come as pg.ErrNoRows

File: pkg/pipeline/CdHandler.go [hunk 2]
```diff
@@ -715,6 +715,55 @@ func (impl *CdHandlerImpl) GetCdBuildHistory(appId int, environmentId int, pipel
...
+		wfGitTriggers := make(map[int]map[int]pipelineConfig.GitCommit)
+		var ciPipelineId int
+		for _, ciWf := range ciWfs {
+			ciPipelineId = ciWf.CiPipelineId
+			wfGitTriggers[ciWf.Id] = ciWf.GitTriggers
+		}
+		ciMaterials, err := impl.ciPipelineMaterialRepository.GetByPipelineIdForRegexAndFixed(ciPipelineId)
+		if err != nil {
+			impl.Logger.Errorw("err", "err", err)
```
Comment (prakash100198) [inline pkg/pipeline/CdHandler.go:737]: put appropriate error message here, not just "err" and also why are we not returning from here where error is encountered? is this on purpose if yes then please put appropriate comment why are we not returning from here

File: pkg/pipeline/CdHandler.go [hunk 3]
```diff
@@ -715,6 +715,55 @@ func (impl *CdHandlerImpl) GetCdBuildHistory(appId int, environmentId int, pipel
...
+			impl.Logger.Errorw("error in fetching ci wfs", "artifactIds", ciArtifactIds, "err", err)
+			return cdWorkflowArtifact, err
+		}
+		wfGitTriggers := make(map[int]map[int]pipelineConfig.GitCommit)
+		var ciPipelineId int
+		for _, ciWf := range ciWfs {
+			ciPipelineId = ciWf.CiPipelineId
+			wfGitTriggers[ciWf.Id] = ciWf.GitTriggers
+		}
+		ciMaterials, err := impl.ciPipelineMaterialRepository.GetByPipelineIdForRegexAndFixed(ciPipelineId)
```
Comment (prakash100198) [inline pkg/pipeline/CdHandler.go:735]: when ciWfs will come as nil or no rows then ciPipelineId will be 0 and here also it will throw error with pg no rows so you need to handle that also

Also is this intentional that in the for loop above ciPipelineId will be assigned of the last ciWf.CiPipelineId and you needed that ciPipelineId only?

**Review by prakash100198 — CHANGES_REQUESTED** [review]

**Review by prakash100198 — APPROVED** [review]

**Review by prakash100198 — DISMISSED** [review]

**Review by prakash100198 — DISMISSED** [review]

**Review by kripanshdevtron — APPROVED** [review]

**Review by kripanshdevtron — APPROVED** [review]
