### PR TITLE
Fix for 1596: Added check for empty prometheus url

### LINKED ISSUE #1596: Not able to update cluster-token from UI if needed
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

If we update a token for any cluster, it throws response 500 error. It updates the token in database but doesn't update the token in respective secret of the cluster

**To Reproduce**

1. Add a cluster to Devtron
2. Generate a new token for the same cluster
3. Update it in cluster configurations

**Expected behavior**

It should update the token and continue the normal functioning

**Current behavior** 

It throws an error on update, then updates only in database but not in respective secret of the cluster

### PR DESCRIPTION
**Pull request by anupdhiran**
# Description
Added fix for issue 1596 where in update cluster request were failing with 500 error

Fixes #1596 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Have tested locally against demo1 environment with valid cluster and trying to update it. Got proper 200 response

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have tested it for all user roles
* [] I have added all the required unit/api test cases

### CODE REVIEW

File: pkg/cluster/ClusterService.go [hunk 1]
```diff
@@ -339,10 +340,18 @@ func (impl *ClusterServiceImpl) Update(ctx context.Context, bean *ClusterBean, u
 	model.PrometheusEndpoint = bean.PrometheusUrl
 
 	if bean.PrometheusAuth != nil {
-		model.PUserName = bean.PrometheusAuth.UserName
-		model.PPassword = bean.PrometheusAuth.Password
-		model.PTlsClientCert = bean.PrometheusAuth.TlsClientCert
-		model.PTlsClientKey = bean.PrometheusAuth.TlsClientKey
+		if bean.PrometheusAuth.UserName != "" {
+			model.PUserName = bean.PrometheusAuth.UserName
```
Comment (kartik-579) [inline pkg/cluster/ClusterService.go:344]: by default string is empty, then why are we implementing this check?

File: pkg/cluster/ClusterServiceExtended.go [hunk 2]
```diff
@@ -143,50 +144,55 @@ func (impl *ClusterServiceImplExtended) Update(ctx context.Context, bean *Cluste
...
+						TlsAuth:    true,
+					}
+					updateDatasourceReq.JsonData = *jsonData
 				}
-				updateDatasourceReq.JsonData = *jsonData
+				updateDatasourceReq.SecureJsonData = secureJsonData
+			}
+			_, err = impl.grafanaClient.UpdateDatasource(updateDatasourceReq, env.GrafanaDatasourceId)
+			if err != nil {
+				impl.logger.Error(err)
```
Comment (kartik-579) [inline pkg/cluster/ClusterServiceExtended.go:191]: can make log more descriptive here

**Review by kartik-579 — CHANGES_REQUESTED** [review]

File: pkg/cluster/ClusterService.go (hunk 1 above)
Comment (anupdhiran) [reply pkg/cluster/ClusterService.go:344]: The problem was that req is having empty strings which ideally doesn't make sense to update in DB if it's just empty string. The parent check above this was trying to do the same thing : `bean.PrometheusAuth != nil` but since it's an object, the check was failing and we were updating the DB with empty values.
