### PR TITLE
fix: invalid runner status

### LINKED ISSUE #5194: Bug: auto cd failing
### 📜 Description

auto cd fails if pre cd is configured

### 👟 Reproduction steps

1) configure pre-cd for a pipeline and keep cd in auto trigger mode.
2) trigger pre-cd and wait for it to complete successfully. 
3) After pre-cd, cd is not triggered even though it was in auto mode . 

### 👍 Expected behavior

cd should be triggered 

### 👎 Actual Behavior

cd does not gets triggered 

### ☸ Kubernetes version

EKS 1.23

### Cloud provider

<details>
EKS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#9867

### PR DESCRIPTION
**Pull request by iamayushm**
# Description

Fixes #5194

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/eventProcessor/in/WorkflowEventProcessorService.go [hunk 1]
```diff
@@ -152,6 +152,16 @@ func (impl *WorkflowEventProcessorImpl) SubscribeCDStageCompleteEvent() error {
 			impl.logger.Errorw("could not get wf runner", "err", err)
 			return
 		}
+
+		if wfr.Status != string(v1alpha1.NodeSucceeded) {
```
Comment (kartik-579) [inline pkg/eventProcessor/in/WorkflowEventProcessorService.go:156]: should this be wfr.Status == string(v1alpha1.NodeSucceeded)?

**Review by kartik-579 — APPROVED** [review]

**Review by nishant-d — APPROVED** [review]

**Review by nishant-d — APPROVED** [review]
