### PR TITLE
sql wire separate

### LINKED ISSUE #950: Allow devtron-core  running in multi mode
# Summary
currently 
1. On startup devtron creates connection with multiple components and startup fails if connection breaks
2. all classes are loaded in memory on startup
  
Due to this we are unable to run devtron partially. for integration with external app we are facing same issue. 

# Proposal

create separate boundary for diff devtron components which are required in external app

### PR DESCRIPTION
**Pull request by nishant-d**
# Description

fixes #950  partially 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test case A
- [ ] Test case B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles

### CODE REVIEW

File: api/restHandler/app/PipelineConfigRestHandler.go [hunk 1]
```diff
@@ -95,9 +96,9 @@ type PipelineConfigRestHandlerImpl struct {
 	application             application.ServiceClient
 	userAuthService         user.UserService
 	validator               *validator.Validate
-	teamService             team.TeamService
-	enforcer                rbac.Enforcer
-	gitSensorClient         gitSensor.GitSensorClient
+	teamService     team.TeamService
```
Comment (pghildiyal) [inline api/restHandler/app/PipelineConfigRestHandler.go:99]: formatting isssue

File: api/restHandler/AppLabelsRestHandler.go [hunk 2]
```diff
@@ -42,13 +43,13 @@ type AppLabelRestHandlerImpl struct {
 	appLabelService app.AppLabelService
 	userAuthService user.UserService
 	validator       *validator.Validate
-	enforcerUtil    rbac.EnforcerUtil
-	enforcer        rbac.Enforcer
+	enforcerUtil rbac.EnforcerUtil
```
Comment (pghildiyal) [inline api/restHandler/AppLabelsRestHandler.go:46]: formating issue

File: api/restHandler/AppListingRestHandler.go [hunk 3]
```diff
@@ -57,9 +58,9 @@ type AppListingRestHandler interface {
 type AppListingRestHandlerImpl struct {
 	application            application.ServiceClient
 	appListingService      app.AppListingService
-	teamService            team.TeamService
-	enforcer               rbac.Enforcer
-	pipeline               pipeline.PipelineBuilder
+	teamService team.TeamService
```
Comment (pghildiyal) [inline api/restHandler/AppListingRestHandler.go:61]: formating issue

File: api/restHandler/ArgoApplicationRestHandler.go [hunk 4]
```diff
@@ -64,17 +65,17 @@ type ArgoApplicationRestHandler interface {
 type ArgoApplicationRestHandlerImpl struct {
 	client                 application.ServiceClient
 	logger                 *zap.SugaredLogger
-	pump                   connector.Pump
-	enforcer               rbac.Enforcer
-	teamService            team.TeamService
+	pump        connector.Pump
```
Comment (pghildiyal) [inline api/restHandler/ArgoApplicationRestHandler.go]: formatting issue

File: api/restHandler/AttributesRestHanlder.go [hunk 5]
```diff
@@ -39,13 +39,13 @@ type AttributesRestHandler interface {
 }
 
 type AttributesRestHandlerImpl struct {
-	logger            *zap.SugaredLogger
-	enforcer          rbac.Enforcer
-	userService       user.UserService
+	logger      *zap.SugaredLogger
```
Comment (pghildiyal) [inline api/restHandler/AttributesRestHanlder.go]: formatting issue

also correct the name of the file

File: api/restHandler/AttributesRestHanlder.go [hunk 6]
```diff
@@ -39,13 +39,13 @@ type AttributesRestHandler interface {
 }
 
 type AttributesRestHandlerImpl struct {
```
Comment (pghildiyal) [inline api/restHandler/AttributesRestHanlder.go:41]: correct the name of file, in Hanler, d is missing

File: api/restHandler/BulkUpdateRestHandler.go [hunk 7]
```diff
@@ -39,9 +40,9 @@ type BulkUpdateRestHandlerImpl struct {
 	application             application.ServiceClient
 	userAuthService         user.UserService
 	validator               *validator.Validate
-	teamService             team.TeamService
-	enforcer                rbac.Enforcer
-	gitSensorClient         gitSensor.GitSensorClient
+	teamService     team.TeamService
```
Comment (pghildiyal) [inline api/restHandler/BulkUpdateRestHandler.go]: formatting issue

**Review by pghildiyal — APPROVED** [review]
