### PR TITLE
chart versionv2

### LINKED ISSUE #146: Helm chart support for apiversion: v2 charts
Helm charts with apiversion: v2 fail to list in app store

### PR DESCRIPTION
**Pull request by nishant-d**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #146

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] added chart repo with chart version v2, the chart should be populated in discover chart 
- [x] deploy chart with api version v2

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates? - NO
* [ ] I've updated documentation as required by this PR.
* [x ] I have performed a self-review of my own code 
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles NA

### CODE REVIEW

File: internal/util/ChartService.go [hunk 1]
```diff
@@ -300,7 +300,7 @@ func (impl ChartTemplateServiceImpl) getDir() string {
 }
 
 func (impl ChartTemplateServiceImpl) CreateChartProxy(chartMetaData *chart.Metadata, refChartLocation string, templateName string, version string, envName string, appName string) (string, *ChartGitAttribute, error) {
-	chartMetaData.ApiVersion = "v1" // ensure always v1
+	chartMetaData.ApiVersion = "v2" // ensure always v1
```
Comment (pghildiyal) [inline internal/util/ChartService.go:303]: change the comment

**Review by pghildiyal — APPROVED** [review]
