### PR TITLE
fix: Security Pagination Count wrong fix

### LINKED ISSUE #3546: Bug: Wrong security scan count on security pagination
### 📜 Description

Wrong security scan count on security pagination

### 👟 Reproduction steps

1. Go to security tab and check security scan count. Actual security scans are different from the number shown on pagination.

### 👍 Expected behavior

There should correct counting of security scans.

### 👎 Actual Behavior

Count of security scans is not correct on pagination.

### ☸ Kubernetes version

EKS 1.25

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3936

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Fixes #3546 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by kartik-579 — APPROVED** [review]

File: internal/sql/repository/security/ImageScanDeployInfoRepository.go [hunk 1]
```diff
@@ -185,7 +185,8 @@ func (impl ImageScanDeployInfoRepositoryImpl) scanListQueryWithoutObject(request
 	}
 	query = query + " INNER JOIN environment env on env.id=info.env_id"
 	query = query + " INNER JOIN cluster clus on clus.id=env.cluster_id"
-	query = query + " WHERE info.scan_object_meta_id > 0 and env.active=true"
+	query = query + " INNER JOIN app ap on ap.id = info.scan_object_meta_id"
```
Comment (vikramdevtron) [inline internal/sql/repository/security/ImageScanDeployInfoRepository.go:188]: scan_object_meta_id is not exactly the appId, it contains other ids based on object type

**Review by vikramdevtron — APPROVED** [review]
