### PR TITLE
fix: User api version for old apis

### LINKED ISSUE #4684: Bug: Use v2 route for user and permission list API & re-add the export APIs
### 📜 Description

Use v2 route for user and permission list API & re-add the export APIs

### 👟 Reproduction steps

.

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### ☸ Kubernetes version

.

### Cloud provider

<details>

</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8542

### LINKED ISSUE #4687: Bug: User listing api breaks, does not compatible with older version of dashboard.
### 📜 Description

In the new feature user listing come up with new look, api and response has been modified along with UI component. In case client is running with the older version of dashboard, user listing will breaks as it does not support existing structure. 

### 👟 Reproduction steps

1. Go to user authorisation.
2. Open user listing.

### 👍 Expected behavior

New release should support older api. 

### 👎 Actual Behavior

Without hard refresh dashboard call older api's and page breaks.

### ☸ Kubernetes version

Any

### Cloud provider

Any

### 🌍 Browser

Chrome

### 🧱 Your Environment

Preview

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8551

### PR DESCRIPTION
**Pull request by Shivam-nagar23**
# Description

Fixes #4684 
Fixes #4687 
## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: api/bean/UserRequest.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ type UserRole struct {
 
 type UserInfo struct {
 	Id            int32        `json:"id" validate:"number,not-system-admin-userid"`
-	EmailId       string       `json:"emailId" validate:"required,not-system-admin-user"`
+	EmailId       string       `json:"email_id" validate:"required,not-system-admin-user"`
```
Comment (kartik-579) [inline api/bean/UserRequest.go:34]: we can have emailId as well and can start using it in newer versions, email_id is anyway incorrect convention and can be deprecated in future

**Review by kartik-579 — DISMISSED** [review]

File: api/bean/UserRequest.go (hunk 1 above)
Comment (Shivam-nagar23) [reply api/bean/UserRequest.go:34]: it has an impact on user creation and updation as well, have to sent this urgently. can be done in future releases

Comment (kartik-579) [reply api/bean/UserRequest.go:34]: add TODO comment so that it does not gets missed later
